### ISSUE TITLE
Adapt to keyboard changes

### ISSUE THREAD

**Issue by albemala** [huri000/SwiftEntryKit#10]
Hello,

I haven't found support or a way to adapt a displayed entry to keyboard showing/hiding, so that for example if the keyboard shows, a centred displayed entry will reposition by translating vertically.

So the question is: how can I change a displayed view position when the keyboard is shown/hid? Or, could you add support for it?

Thank you!

**Comment by huri000** [comment]
Hi, 
SwiftEntryKit doesn't currently support keyboard changes, but I'm considering:
1. Adding a feature that enables you to set a top or bottom position dependency in another given view.
2. Adding a feature the makes the entry listen to keyboard changes, thus clip the bottom to the top of the keyboard with offset.

The plan is to add at least one of those in the next couple of weeks.

Thanks,

**Comment by albemala** [comment]
N. 2 would be awesome, thanks!

**Comment by huri000** [comment]
@albemala, Check out the new release (0.2.0) 🎉

**Comment by albemala** [comment]
Thank you very much! I'll give it a try and let you know, cheers.
