### ISSUE TITLE
Queue of Entries

### ISSUE THREAD

**Issue by huri000** [huri000/SwiftEntryKit#103]
**Is your feature request related to a problem? Please describe.**
Right now SwiftEntryKit is not able to handle multiple entries. Every new entry drops the previous one.
The currently supported approach to this is to prioritize each entry using displayPriority property in EKAttributes.
SwiftEntryKit should allow other approaches as well - for example, a queue of entries, where each one is displayed in its turn.

**Describe the solution you'd like**
1. Add a data structure for caching new entries. That construct should abstract a queueing mechanism.
2. Add multiple heuristics to the queue: queue by priority, by chronological order.
3. Refactor display priority to another construct that embodies the way in which new entries are treated.

**Comment by huri000** [comment]
@Blackjacx - Check [it](https://github.com/huri000/SwiftEntryKit/pull/105) out if you wish. Let me know your thoughts about the feature and the style.
I also plan to allow simultaneous display of entries in the future (very soon I hope) - one on top of the other.

**Comment by Blackjacx** [comment]
I'll set it on my todo list and check it out when I have time again 👍

**Comment by huri000** [comment]
Hi - I've merged the last pull request and can be used from now on using `0.7.0` or any higher version of SwiftEntryKit.
Cheers! 🎉
