### ISSUE TITLE
The notification doesn't respect rotation restrictions

### ISSUE THREAD

**Issue by dchakarov** [huri000/SwiftEntryKit#104]
**Describe the bug**
If you rotate the phone while the notification is on screen, the screen rotates even if the rotation is disabled for that navigation controller.

**To Reproduce**
1. Create a project allowing all orientations
2. Create a view controller inside a navigation controller
3. Restrict the navigation controller to portrait
4. Trigger a topFloat item (for example) and rotate while it is on screen

**Expected behavior**
The screen should be locked in portrait mode regardless of whether the notification is displayed or not.

**iPhone (please complete the following information):**
 - Device: iPhoneX
 - iOS Version: iOS12
 - Xcode Version: 9.4.1
 - Dependency Manager Version: Carthage 0.30.1
 - SwiftEntryKit Release # 0.6.0

**Screenshots / Video Links**
![img_1567](https://user-images.githubusercontent.com/1482285/45172105-38f11a00-b1fc-11e8-9366-587ae56a7178.PNG)

[IMG_1568.TRIM.MOV.zip](https://github.com/huri000/SwiftEntryKit/files/2357960/IMG_1568.TRIM.MOV.zip)

**Comment by huri000** [comment]
Hi,
SwiftEntryKit doesn't inherit automatically the navigation controller rotation restrictions. It is displayed in a separate window and agnostic to any lower windows context.
You need to set `isRotationEnabled` to `false`, likewise:
`attributes.positionConstraints.isRotationEnabled = false`.
Please let me know if that works for you.

**Comment by dchakarov** [comment]
It works, thank you!
