### ISSUE TITLE
Swift 4.2 Support

### ISSUE THREAD

**Issue by Blackjacx** [huri000/SwiftEntryKit#108]
Hey there! Just configured everything for Swift 4.2 but unfortunately SwiftEntryKit and/or QuickLayout does not support it yet. A fix is welcomed :-)

**Comment by huri000** [comment]
Hi! You’re right. Unfortunately I won’t be able to make that adjustment within the next 2 weeks (I won’t be near my mac).
I’ll handle it right after Sep 26. In the meantime, you can fork those projects and make the modifications. 🙂

**Comment by huri000** [comment]
Hi - until SwiftEntryKit and QuickLayout support Swift 4.2 you can add the following in your Podfile in order to make the project run smoothly.

```ogdl
swift_4_2_pod_targets = ['SwiftEntryKit', 'QuickLayout']
post_install do | installer |
    installer.pods_project.targets.each do |target|
        if swift_4_2_pod_targets.include?(target.name)
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
```

**Comment by Kaspik** [comment]
So it looks like SwiftEntryKit is ready and the last thing is QuickLayout - `QLCompatibility.swift`. Anything we can help you with or are you already on it today @huri000 ? :)

**Comment by Kaspik** [comment]
Yeah, it does, I just wanted to say that it looks like it's already 4.2 compatible except this one file - so if you wanna help with PR or if you are on it and it would be waste of time. :)

**Comment by huri000** [comment]
Thanks, @Kaspik! I'm on it :-)
I'll keep you posted on this thread.

**Comment by huri000** [comment]
@Kaspik, @Blackjacx, SwiftEntryKit supports Swift 4.2 natively as of version **0.8.0**.
Cheers! 🎉

**Comment by huri000** [comment]
Also - please note that additional changes must be made in order to adapt to 0.7.0 and above. See [CHANGELOG](https://github.com/huri000/SwiftEntryKit/blob/master/CHANGELOG.md) for more information.

**Comment by Kaspik** [comment]
Thank you! I was already using 0.7 so there are just good news for me :)

**Comment by huri000** [comment]
Hi - I've made a necessary fix to the swift version for QuickLayout's and SwiftEntryKit's podspecs. Please use **0.8.1** instead of **0.8.0**. This fix enabled developers to use Xcode 10 and lower than 4.2 swift version of the project's targets without specifying [this](https://github.com/huri000/SwiftEntryKit/issues/108#issuecomment-425374479) in their Podfile (quite dirty approach that was). ;-)
