### ISSUE TITLE
CocoaPods issue

### ISSUE THREAD

**Issue by mrott** [huri000/SwiftEntryKit#11]
I'm getting this issue: [!] Unable to find a specification for `SwiftEntryKit (= 0.1.5)`. 
After setting the git path I get another error about QuickLayout: [!] Unable to find a specification for `QuickLayout (= 1.0.13)` 
Running on CocoaPods 1.5.2

**Comment by huri000** [comment]
Possible duplicate: [issue](https://github.com/huri000/SwiftEntryKit/issues/4).

**Comment by huri000** [comment]
Closing due to duplication.
