### ISSUE TITLE
numberOfLines property

### ISSUE THREAD

**Issue by HermanKayy** [huri000/SwiftEntryKit#111]
I currently have an ImageNote that acts as an alert to display text. When the text gets too long however, the text just extends past the alert itself. I tried changing the line numbers property but it doesn't work. Any suggestions/fix for this? Thanks

**Comment by huri000** [comment]
Hi @HermanKayy!
I'll check it out during the next few days and keep you posted. 
Thanks!

**Comment by huri000** [comment]
Well, I don't remember if it is some kind of bug or it should have been the design itself that allow minimal messages only. I'm assuming it is a bug.
There is a fix available on **0.7.2** (The [Pull Request](https://github.com/huri000/SwiftEntryKit/pull/114) has the technical implementation info).
Cheers! 🎉
