### ISSUE TITLE
How to check is there any alert on the screen?

### ISSUE THREAD

**Issue by Banck** [huri000/SwiftEntryKit#12]
Hello!
I have two questions:
1) Is there any way to check if there is alert on the screen at this moment?
2) If no, then how can I detect when alert was dismissed by user swipe and other actions?
Thanks for this beautiful lib!

**Comment by huri000** [comment]
Hi @Banck,
`EKAttributes.isPresenting` should be what you are looking for I think. 
It's a static computed property. FYI, I'm gonna internalize it in the next version, and instead, expose it publicly via SwiftEntryKit as a class property.
And thank you for the question - I'll make sure it'll be documented in the README in the next version release.

**Comment by Banck** [comment]
Yeah, thank you! I just thought, that this property should be in SwiftEntryKit and was finding there.
Thank you a lot!

**Comment by huri000** [comment]
Glad you found it helpful!

**Comment by Banck** [comment]
For everyone who is looking for it , in 0.2.0 version now there is `isCurrentlyDisplaying` class property in SwiftEntryKit.
