### ISSUE TITLE
Method .becomeFirstResponder() does NOT work

### ISSUE THREAD

**Issue by omidgolparvar** [huri000/SwiftEntryKit#123]
**Describe the bug**
When I present  a `UIViewController` that has a `UITextField` or `UITextView`, I can NOT use `.becomeFirstResponder()` to focus textFields or textViews.
I tried:
```
override func viewDidLoad() {
    super.viewDidLoad()
    textField_Email.becomeFirstResponder()
}
```
and

```
override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    textField_Email.becomeFirstResponder()
}
``` 
and even:
```
@IBAction func test(_ sender: UIButton) {
    textField_Email.becomeFirstResponder()
}
```

**iPhone (please complete the following information):**
 - Device: iPhone 8
 - iOS Version: iOS 12
 - Xcode Version: 10
 - Dependency Manager Version: CocoaPods 1.4.0
 - SwiftEntryKit Release # 0.5.6

**Comment by huri000** [comment]
Have you tried displaying the window as key? (See documentation for ‘SwiftEntryKit.display’).

**Comment by huri000** [comment]
@omidgolparvar - Have you tried what I suggested?

**Comment by omidgolparvar** [comment]
@huri000 I will try it and share results. Thanks.

**Comment by omidgolparvar** [comment]
@huri000 Hello again my friend 😊
I used `SwiftEntryKit.display(entry:, using:, presentInsideKeyWindow: true)` and it works perfectly. 

Thanks. 😋

**Comment by huri000** [comment]
Awesome! 🎉
