### ISSUE TITLE
Xcode report an error: 'EKAttributes' has no member 'windowLevel'

### ISSUE THREAD

**Issue by LayChan** [huri000/SwiftEntryKit#124]
Hi, I had a trouble in use, Xcode report an error: 'EKAttributes' has no member 'windowLevel', but this attribute exists in 'EKAttributes.swift'

Xcode Version 10.0
Dependency Manager : CocoaPods
SwiftEntryKit Release : 0.8.2

![default](https://user-images.githubusercontent.com/15124524/46577369-dc5e6600-ca18-11e8-933a-3bed199b1e89.png)

**Comment by huri000** [comment]
Hi - I assume you managed to resolve it. I’d love to know what cause the issue 🙂

**Comment by ktkanishka** [comment]
Hi, I'm having the same issue. Can you please help?

**Comment by LayChan** [comment]
[image1.jpeg]

发自我的 iPhone

在 2018年10月14日，10:34，Kanishka Raveendra <notifications@github.com<mailto:notifications@github.com>> 写道：


Hi, I'm having the same issue. Can you please help?
