### ISSUE TITLE
Xcode 10 Errors

### ISSUE THREAD

**Issue by MenuHunt** [huri000/SwiftEntryKit#125]
As you can see the attached screenshot, I got a bunch of errors when migrating to Xcode 10. I did not see these errors before. I could unlock the pod and fix the deprecated code by myself, but even after I did that, my app crashes. See the second screenshot for what I did and the error on the print line. It seems caused by EKAttributes.

![notificationbannerswift_errors](https://user-images.githubusercontent.com/21147774/46577972-48f54880-c9b8-11e8-88ce-2b3d760ecedb.png)
![notificationbannerswift_crash](https://user-images.githubusercontent.com/21147774/46577985-92459800-c9b8-11e8-8b2d-6702aeb9838b.png)

**Comment by huri000** [comment]
What version of SwiftEntryKit are you using (0.8.2) is Xcode 10 compatible.

**Comment by huri000** [comment]
What version of SwiftEntryKit are you using (0.8.2) is Xcode 10 compatible.

**Comment by MenuHunt** [comment]
The deployment target was iOS 11.3

**Comment by MenuHunt** [comment]
You are right. I am sorry for that. But what caused the crash was still the SwiftEntryKit code as shown in the other screenshot. I tried to create a new project using SwiftEntryKit and it worked. I don't why that piece of code always crashed in my current app. Even if I move the print line to right after the creation of EKAttributes, var attributes = EKAttributes.topFloat, it gives me the same error. Very weird. Anyway, you can close this problem. I will have to find a way around.

**Comment by huri000** [comment]
One of those typical migration problems IMO.
Have you tried the following?
1. `pod cache clean --all`
2. `pod deintegrate`
3. Clean the project, build folder and derived data.
4. `pod install`
5. Run again.

**Comment by huri000** [comment]
And it might also happen because your project/target is defined with Swift version which is less than 4.2. When you opened the project using Xcode 10, it generated a Swift4.2 project by default. If it is te case - please have a look at: https://github.com/huri000/SwiftEntryKit/issues/122#issuecomment-427670349

**Comment by MenuHunt** [comment]
Oh, boy. I did use 4.1. I will try your suggestion and let you know. Thanks

**Comment by huri000** [comment]
Thanks, @MenuHunt! I'm keeping the issue open until then. :-)

**Comment by MenuHunt** [comment]
It took me a while to update the syntax for using Swift 4.2. Yeah! That was the problem. The issue has been fixed. Thanks so much! You are the man!

**Comment by huri000** [comment]
Great! 💯
