### ISSUE TITLE
Getting error while enter below line of code

### ISSUE THREAD

**Issue by sivadoddi** [huri000/SwiftEntryKit#126]
**Describe the bug**
I am getting following error while calling below lines of code 
        infoViewConfig.presentationContext = .window(windowLevel: UIWindowLevelNormal)
and  
        attributes.windowLevel = .alerts

error message : 
        Value of type 'EKAttributes' has no member 'windowLevel'
        Value of type 'SwiftMessages.Config' has no member 'presentationContext'; did you mean 'presentationStyle'?

**Comment by huri000** [comment]
What version of SwiftEnryKit, Xcode, and Swift are you using? Also, what is the Swift version of your target?

This below is not a SwiftEntryKit related issue but another library.
> Value of type 'SwiftMessages.Config' has no member 'presentationContext'; did you mean 'presentationStyle'?

**Comment by sivadoddi** [comment]
I used Swift 4.2, Even I checked with demo application same thing happed to me.

**Comment by huri000** [comment]
It might be the cached data for your project in the build directory / derived data folder caused this. So I would try the following (I couldn’t reproduce the issue so I’m shooting in multiple directions):
1. Clean Build + Build Directory.
2. Quit Xcode
3. Delete Derived Data.
4. `pod deintegrate`, `pod cache clean --all` and `pod install` (the last will `pod repo update` by default in case the cache is already cleaned up).
5. Open Xcode and run the `project.xcworkspace`

Also, please verify that your have Xcode 10 which not a beta.

Here is [a working host project](https://github.com/huri000/SwiftEntryKit/files/2452118/testingCrash.zip) I've been experimenting with. Please try it and let me know if the attached project and suggested steps work for you.

**Comment by linshizai** [comment]
@huri000 I met the same error, though execute the code you provided above, I have to use 0.6.0 version which compile success

**Comment by huri000** [comment]
@sivadoddi - Please refer to this [thread](https://github.com/huri000/SwiftEntryKit/issues/127#issue-367742844) for a solution.

**Comment by huri000** [comment]
I believe this issue is resolved (derived from resolving [this one](https://github.com/huri000/SwiftEntryKit/issues/127#issue-367742844)). The README installation section was updated with new info regarding the installation process.
Closing for now.
