### ISSUE TITLE
iPhone x issue

### ISSUE THREAD

**Issue by Banck** [huri000/SwiftEntryKit#13]
Hey!
I have an issue with iPhone X and safe area. 
For some reason alert is placed above bottom safe area and when I scroll it, the alert view is increase. see the video bellow. How can I put my alert view on the bottom?
video: http://dropmefiles.com/gzaww

code is here:

        var attributes: EKAttributes
        
        attributes = .bottomFloat
        attributes.windowLevel = .alerts
        attributes.hapticFeedbackType = .success
        attributes.screenInteraction =  .forward
        attributes.entryInteraction = .absorbTouches
        attributes.scroll = .enabled(swipeable: true, pullbackAnimation: .jolt)
        attributes.screenBackground = .color(color: .clear)
        attributes.entryBackground = .color(color: .clear)
        attributes.entranceAnimation = .init(scale: .init(from: 0.9, to: 1, duration: 0.4, spring: .init(damping: 1, initialVelocity: 0)), fade: .init(from: 0, to: 1, duration: 0.3))
        attributes.exitAnimation = .init(scale: .init(from: 1, to: 0.9, duration: 0.4, spring: .init(damping: 1, initialVelocity: 0)), fade: .init(from: 1, to: 0, duration: 0.3))
        attributes.displayDuration = .infinity
        attributes.border = .value(color: .black, width: 0.5)
        attributes.shadow = .active(with: .init(color: .black, opacity: 0.3, radius: 5, offset: .zero))
        attributes.positionConstraints.size = .init(width: .constant(value: min(UIScreen.main.bounds.width, UIScreen.main.bounds.height)), height: .intrinsic)
        attributes.positionConstraints.verticalOffset = 0
        attributes.positionConstraints.safeArea = .empty(fillSafeArea: true)
        return attributes
```

**Comment by huri000** [comment]
Hi,
Thanks for reporting the issue.
To achieve the intended behavior you should set `safeArea` to `.overridden` likewise:
`attributes.positionConstraints.safeArea = .overridden`.
Afer investigating this issue, even when you set it like the above, it won't work since there is a bug. 
I'll make sure I release a fix for it in the next version.

**Comment by huri000** [comment]
About the other issue - the `drop` of the view as you scroll. In case your view is initialized from a nib file, you might want to unmark `Safe Area Layout Guide` in order to prevent the bottom side of the entry from being obscurred.

**Comment by huri000** [comment]
Hi,
I've released a fix in version 0.2.0.
Please check it out.

**Comment by Banck** [comment]
Now all is fine. Thank you very much!
