### ISSUE TITLE
Quick Layout dependency compile error.

### ISSUE THREAD

**Issue by HayTran94** [huri000/SwiftEntryKit#130]
**Describe the bug**
Install SwiftEntryKit via CocoaPoad and build. But Quick Layout dependency compile error.

**To Reproduce**
1. Install project via CocoaPod
2. Build project
3. QLCompatibility.swift compile error. 
'Attribute' is not a member type of 'NSLayoutConstraint'.
'Relation' is not a member type of 'NSLayoutConstraint'.

**Expected behavior**
QuickLayout can build successfully.

**Screenshots**
![alt text](https://raw.githubusercontent.com/HayTran94/BugReportImage/master/SwiftEntryKit.png)

**Comment by huri000** [comment]
Hi @HayTran94 - 
What is the version of `SwiftEntryKit`? 
What are the Swift and Xcode versions?

**Comment by HayTran94** [comment]
Hi @huri000 

SwiftEntryKit version: 0.8.2.
Xcode version: 9.4 (9F1027a).
Swift version: 4.1.

**Comment by huri000** [comment]
Until you upgrade to Xcode 10 & Swift 4.2 - please pod install `'SwiftEntryKit', '0.7.2'`.
Let me know if that works for you.

**Comment by HayTran94** [comment]
Hi @huri000 

Thank you very much. It work. You are very kind and generous. Love you <3 !

**Comment by huri000** [comment]
Glad I could help :-)
