### ISSUE TITLE
EKAttributes+PositionConstraints initializer typo?

### ISSUE THREAD

**Issue by jgoodrick** [huri000/SwiftEntryKit#131]
**Describe the bug**
The currently provided default initializer does not actually use the passed in max size, ignoring it during initialization.

**To Reproduce**
1. Go to 'EKAttributes+PositionConstraints.swift'
2. Scroll down to 'public init(verticalOffset:size:maxSize:)'
3. See error:
            self.maxSize = .intrinsic

**Expected behavior**
I would have expected the third line to read:
            self.maxSize = maxSize

**iPhone (please complete the following information):**
 - Device: iPhoneX
 - iOS Version: iOS12
 - Xcode Version 10.0
 - Dependency Manager Version: CocoaPods 1.5.3
 - SwiftEntryKit Release # 0.8.2

**Comment by huri000** [comment]
Hi @Sndrsn! My bad, thanks for letting me know!
You are always welcome to fork and pull request fixes for bugs.
Since I intend on releasing a new patch version in the next few days, let me know if you wish to pull-request a hotfix for it today or tomorrow.
