### ISSUE TITLE
Error when install the pod

### ISSUE THREAD

**Issue by KekeTSC** [huri000/SwiftEntryKit#138]
At the moment I install the pod, version 0.8.4, I'm on xCode 10.1, I have an error when building all my targets, the error says me:

error: /Users/XXX/Desktop/MyProject/Pods/Pods/Target Support Files/Pods-MyTarget/Pods-MyTarget.debug.xcconfig: unable to open file (in target "MyTarget" in project "MyProject") (in target 'MyTarget')

Can someone help me ? The library is exactly what I want and what I need.

Thank you !

**Comment by huri000** [comment]
Hi! I'll try to check what that error means later today, but I think this error is an indication of a general CocoaPods problem and not necessarily a SwiftEntryKit issue. I would try to recheck that:
- I open the workspace and not the project file.
- Clean and delete project's derived-data.
- `pod cache clean --all`
- `pod deintegrate`
- `pod install`
- build again.

Let me know if that works for you.

**Comment by KekeTSC** [comment]
Finally, an other developper test the same commands as me, and it works. I don't know why
