### ISSUE TITLE
How do I add an action to EKProperty.ButtonContent for Alert

### ISSUE THREAD

**Issue by dm2112** [huri000/SwiftEntryKit#142]
<img width="1038" alt="screen shot 2018-12-08 at 6 41 40 pm" src="https://user-images.githubusercontent.com/36523022/49692470-f6035300-fb18-11e8-99c1-e63516bc9d17.png">
I have tried calling my action "deleteAction and then putting it in EKProperty.ButtonContent(... action: deleteAction) but nothing happens when I press the button in the aler.

**Comment by huri000** [comment]
Hi @dm2112,

You basically need to make sure you embed that `ButtonContent` within another entry descriptor. Also, make sure to inject it to the entry preset. 
There are pretty specific examples inside the example project, I strongly encourage you to check them out.

**Comment by dm2112** [comment]
Thank you!

**Comment by ShvetsJr** [comment]
I noticed that action is called only if I press on the button and than drag outside of the button boundaries. Not on the button tap. Looked at example but I pass action via function so its a bit different. Any thoughts?

**Comment by ShvetsJr** [comment]
I am doing something like this 

`let actionButton = EKProperty.ButtonContent(label: actionTitle, backgroundColor: Colors.white, highlightedBackgroundColor: Colors.red, contentEdgeInset: 12, action: onClick)`

**Comment by arkilis** [comment]
@ShvetsJr I met the same thing here. action is not called at all.

**Comment by DanielZanchi** [comment]
same for me, action not called:
```
let manualSelectorButton = EKProperty.ButtonContent(label: .init(text: "Manual Selector", style: .init(font: UIFont.systemFont(ofSize: 18), color: buttonTitleColor)), backgroundColor: buttonBackgroundColor, highlightedBackgroundColor: buttonTitleColor.withAlphaComponent(0.05)) {
            self.showMaskView(imageToMask: image)   
        }
```

**Comment by ngo275** [comment]
Had the same issue and solved it by modifying the `attributes` property. 

```
var attributes = EKAttributes.topFloat
attributes.entryInteraction = .absorbTouches
```
