### ISSUE TITLE
Completion block issue

### ISSUE THREAD

**Issue by Banck** [huri000/SwiftEntryKit#144]
**Describe the bug**
Hello!
Completion block doesn't work when there is no alert on the screen. Because you this code in dismiss method:
```
guard let rootVC = rootVC else {
            return
        }
```
I think in this case you have to call completion block.

 - SwiftEntryKit Release # 0.8.6

**Comment by Banck** [comment]
Hello!
Yes, I imagined it as a completion block with some parameter like status. 
Well, yes, I think this is too much now, because we can check whether an alert is displayed or not

**Comment by huri000** [comment]
O.K. I'm closing this. Thanks!
