### ISSUE TITLE
windowLevel in attribute doesn't work

### ISSUE THREAD

**Issue by Banck** [huri000/SwiftEntryKit#145]
**Describe the bug**
Hello! I have a strange issue. I have a SwiftEntryKit's alert (from the xib) on the screen and then I display UIAlertController.
The issue is that UIAlertController shows bellow SwiftEntryKit's alert whatever Window Level I put in the attribute. (I've tested with normal, alert and status bar)
Attribute type - bottomFloat
**iPhone (please complete the following information):**
 - iOS Version: **iOS 10, 11, 12**
 - Xcode Version: **10.1**
 - SwiftEntryKit Release: **0.8.6**

**Comment by huri000** [comment]
Hi @Banck! 
That's an interesting use case. I'll check this out and let you know the results.

**Comment by huri000** [comment]
Hi @Banck - are you trying to present `UIAlertController`, right?
If so, an alert controller is presented just like a regular `UIViewController`. It's in the context of a presenting view controller, (unlike the deceased `UIAlertView` which was presented in a top window, as far as I recall). Therefore, it's impossible to display the alert not in the context of a view controller unless you are willing to do modifications and display it - some ideas to bypass it:
1. Remove the entry and display it.
2. Use SwiftEntryKit's [queue](https://github.com/huri000/SwiftEntryKit#enqueue) with a customized view controller that presents the entry after the previous entry is dequeued.
3. There is also this StackOverflow [thread](https://stackoverflow.com/questions/26554894/how-to-present-uialertcontroller-when-not-in-a-view-controller) which I found pretty interesting.

Let me know your thoughts.

**Comment by huri000** [comment]
@Banck - In your particular case, I think the best workaround is using `UIViewController` as an entry and presenting the `UIAlertController` inside it instead.
I'm closing it since it's not a library issue (see my previous comment for explanation).
