### ISSUE TITLE
Crash On Displaying Entry

### ISSUE THREAD

**Issue by Smiller193** [huri000/SwiftEntryKit#147]
**Describe the bug**
I followed the example on displaying a bottom float. I create the attributes and call display but it crashes as soon as I try to display it

    @objc func handleAttend(isAttending:Bool){
        
        var attributes = EKAttributes.bottomFloat
        attributes.hapticFeedbackType = .success
        attributes.entryBackground = .color(color: .white)
        attributes.entryInteraction = .delayExit(by: 3)
        attributes.scroll = .enabled(swipeable: true, pullbackAnimation: .jolt)
        attributes.statusBar = .dark
        attributes.positionConstraints.maxSize = .init(width: .constant(value: UIScreen.main.minEdge), height: .intrinsic)
                
        floatCellSelected(with: attributes, row: 0)
        
        // 2
        if (isAttending) {
            
            AttendService.setIsAttending(!((isAttending)), from: currentEvent) { [unowned self] (success) in
                // 5
                
                defer {
                    self.isUserInteractionEnabled = true
                }
                
                // 6
                guard success else { return }
                
                // 7
                self.currentEvent?.isAttending = !((self.currentEvent!.isAttending))
                
                self.currentEvent?.currentAttendCount += !((self.currentEvent!.isAttending)) ? 1 : -1
                self.actionLabel.text = "Confirm Attendance"
            }
            
        }else{
            
            AttendService.setIsAttending(!((isAttending)), from: currentEvent) {[unowned self] (success) in
                // 5
                
                defer {
                    self.isUserInteractionEnabled = true
                }
                
                guard success else { return }
                
                self.currentEvent?.isAttending = !((self.currentEvent!.isAttending))
                
                self.currentEvent?.currentAttendCount += !((self.currentEvent!.isAttending)) ? 1 : -1
                self.actionLabel.text = "Attendance Confirmed"
    
            }
            
        }
        
    }
    
    //float for attendacne confirmation
    private func floatCellSelected(with attributes: EKAttributes, row: Int) {
        guard let eventTitle = currentEvent?.currentEventName.capitalized else {
            return
        }
        guard let eventImage = currentEvent?.currentEventImage else{
            return
        }
        
        
        Alamofire.request(eventImage).responseImage { response in
            debugPrint(response)
            if let image = response.result.value {
                
                switch row {
                case 0:
                    let title = "Attendance Removed"
                    let desc = "Sorry to see that you changed your mind about attending \(eventTitle)"
                    self.showNotificationMessage(attributes: attributes, title: title, desc: desc, textColor: .black, imageName: image)
                case 1:
                    let title = "Attendance Confirmed"
                    let desc = "Congratulations your attendance has been confirmed for \(eventTitle)"
                    self.showNotificationMessage(attributes: attributes, title: title, desc: desc, textColor: .black, imageName: image)
                default:
                    break
                }
            }
        }
    
    }
    
    
    // Bumps a notification structured entry
    private func showNotificationMessage(attributes: EKAttributes, title: String, desc: String, textColor: UIColor, imageName: UIImage? = nil) {
        let title = EKProperty.LabelContent(text: title, style: .init(font: MainFont.medium.with(size: 16), color: textColor))
        let description = EKProperty.LabelContent(text: desc, style: .init(font: MainFont.light.with(size: 14), color: textColor))
        var image: EKProperty.ImageContent?
        if let imageName = imageName {
            image?.image = imageName
        }
        
        let simpleMessage = EKSimpleMessage(image: image, title: title, description: description)
        let notificationMessage = EKNotificationMessage(simpleMessage: simpleMessage)
        
        let contentView = EKNotificationMessageView(with: notificationMessage)
        SwiftEntryKit.display(entry: contentView, using: attributes)
    }

Im not sure what is making it crash but I am running this on ios 12 with an iphone X and XCode 10.2
It crashes here specifically.

      public class func display(entry view: UIView, using attributes: EKAttributes, presentInsideKeyWindow: Bool = false, rollbackWindow: RollbackWindow = .main) {
            DispatchQueue.main.async {
                EKWindowProvider.shared.display(view: view, using: attributes, presentInsideKeyWindow: presentInsideKeyWindow, rollbackWindow: rollbackWindow)
            }
        }

**Comment by huri000** [comment]
Hi! 
What is the SwiftEntryKit version and your project’s Swift version?
Could you screenshot the stack trace with exception and Swift error breakpoints?
Thanks!

**Comment by Smiller193** [comment]
<img width="1280" alt="screen shot 2019-01-02 at 12 56 26 pm" src="https://user-images.githubusercontent.com/16108750/50604724-dfd58200-0e8d-11e9-9d6e-59e9e1909e44.png">


SwiftEntryKitVersion - 0.8.4
Swift - 4.2

**Comment by huri000** [comment]
I think that something isn't synced correctly in your local repo cache. Deleting and installing sometimes help.
Nothing changed from `0.8.4` to `0.8.6` in that area - only some minor bug fixes, so you can install `0.8.6` in the process without worrying much.

**Comment by Smiller193** [comment]
I hope this works I really want to use this library

**Comment by Smiller193** [comment]
yeah none of that helped

**Comment by huri000** [comment]
@Smiller193, LOL. Well, what is the CocoaPods version you are using? 
Can you tell me if you are experiencing this issue using the following side project?
[swiftentrykittest.zip](https://github.com/huri000/SwiftEntryKit/files/2722036/swiftentrykittest.zip)

**Comment by huri000** [comment]
Hi @Smiller193 - I was able to reproduce it using "Swift 4" value as Swift Language Version in the target's build settings.
Are you sure your **target**'s Swift Language Version is `4.2` and not `4`?

<img width="702" alt="screen shot 2019-01-02 at 11 13 00 pm" src="https://user-images.githubusercontent.com/5504255/50612793-fe666800-0ee3-11e9-8ab2-7afde8a70fa3.png">

**Comment by Smiller193** [comment]
checking now

**Comment by Smiller193** [comment]
yeah that fixed it

**Comment by huri000** [comment]
Glad I could help! 🎉
