### ISSUE TITLE
How would I go about setting data to the custom popup?

### ISSUE THREAD

**Issue by 4ndrewHarri5** [huri000/SwiftEntryKit#151]
How would I set **data** to the custom nib pop up? For example, I have a user object which I want to set to the nib. I then want to display that users profile image and name which is on the nib from the data that was passed in. This question [here](https://stackoverflow.com/questions/54144535/swiftentrykit-custom-pop-up-nib-not-loading-data) has all of the information. I can't seem to find any documentation on this topic. Thank you.

**Comment by huri000** [comment]
Hi @4ndrewHarri5!
According to your code, things should work properly for you but for some reason, they don't. 
Yet, `SwiftEntryKit` custom views work just like any other view. 
Have you tried just adding this view a subview and see if there is a difference?

**Comment by huri000** [comment]
O.K. 
Think you could send me a side project with that code? 
I'll do my best to diagnose your problem.

**Comment by 4ndrewHarri5** [comment]
cheers! I will get back to you with it in a few hours

**Comment by 4ndrewHarri5** [comment]
Hi again. This is a simplified version of the project. The problem is still the same. Appreciate your time to take a look. 

[UserPreviewPopUp.zip](https://github.com/huri000/SwiftEntryKit/files/2751294/UserPreviewPopUp.zip)

**Comment by 4ndrewHarri5** [comment]
Thanks for clearing that up. I wasn't sure on how to go about it. I noticed userRequestView was unused, I got the impression that fromNib() had to be called for the popup to be shown

**Comment by huri000** [comment]
Cheers! I’m closing the issue now. 🎉
