### ISSUE TITLE
how to set form field delegate?

### ISSUE THREAD

**Issue by brainloadtechtechnologies** [huri000/SwiftEntryKit#152]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by brainloadtechtechnologies** [comment]
how to set form field delegate?

**Comment by huri000** [comment]
Hi @brainloadtechtechnologies!
You can setup lifecycle event for an entry using:
```Swift
attributes.lifecycleEvents.willDisappear = { 
/* Extract data here */ 
}
```
Extract the data from `EKProperty.TextFieldContent` instance using `textContent` property (which would give you the raw text for a specific text field.
Let me know if that works for you.

**Comment by brainloadtechtechnologies** [comment]
Thanks for replying. I want delegate for specific textfield not text content.

**Comment by huri000** [comment]
Sorry, I don't think it'll be implemented any time soon, since there are endless possibilities for supporting features, and the presets should supply (IMHO) the minimal necessary level of abstraction.

**Comment by brainloadtechtechnologies** [comment]
thanks, i did it by modifying SwiftEntryKit.

**Comment by huri000** [comment]
Closing for now.
