### ISSUE TITLE
Can't set titleToDescription distance on EKNotificationMessage

### ISSUE THREAD

**Issue by fahlout** [huri000/SwiftEntryKit#157]
Cannot seem to set the inset between title and description on my EKNotificationMessage. Inset doesn't have any public initializers. I'd like to set the titleToDescription distance.

Release: 0.8.8

**Comment by huri000** [comment]
Hi @fahlout!
Apologies for the delay. I'll look into it in the next few days and see what I can do.

**Comment by huri000** [comment]
Hi @fahlout, this feature is supported in 0.8.8. Check out `EKNotificationMessage`'s public initializer. It recieves a parameter named `insets` of type `EKNotificationMessage.Insets` that has a property called `titleToDescription` which is exactly what you need.

```Swift
var insets = EKNotificationMessage.Insets.default
insets.titleToDescription = 20
let notificationMessage = EKNotificationMessage(simpleMessage: simpleMessage, insets: insets)
```

**Comment by huri000** [comment]
It seems to me that if my previous comment provides you what you need, the issue can be closed.
Of course, in case it does not enough, let me know. :-)
