### ISSUE TITLE
custom exit and entrance animations

### ISSUE THREAD

**Issue by 4ndrewHarri5** [huri000/SwiftEntryKit#159]
How would I go about creating custom exit and entrance animations? For example, an exit animation which instead of exiting down would exit to the left, or to the right? Thank you

**Comment by huri000** [comment]
@4ndrewHarri5, short answer, you can't. Horizontal transitions aren't currently supported.

The reason you cannot do it lies in the way things are currently built. 
I would recommend re-editing this issue clearly according to the provided feature format, specifically with the things you want in the feature.

**Comment by Dfmarulanda** [comment]
There is a way to implement a right entry view? As a right menu drawer

**Comment by huri000** [comment]
@Dfmarulanda, No. If there is any change, I'll keep you updated under this issue.

**Comment by huri000** [comment]
Closing as this idea hasn't been addressed so far, and I don't see it implemented in the intermediate future.

**Comment by Jayxiang** [comment]
I want this feature, too
