### ISSUE TITLE
Animation with sequence of images

### ISSUE THREAD

**Issue by Lweek** [huri000/SwiftEntryKit#160]
**Is your feature request related to a problem? Please describe.**
My application does some work in background. During waiting I present topNote with information about running process. I would love to make it more candy with animated sequence of rotating cogs.

**Describe the solution you'd like**
Add new `EKParameter` for array of UIImages. Alternative init for `EKSimpleMessage` where image parameter could be array of images. This array will be then passed to `UIImageView.animationImages` and start animating after note will be fully presented and stop animating before dismiss.

**Comment by huri000** [comment]
Hi @Lweek,
That's a nice idea. I'll try getting it done it this week.

**Comment by Lweek** [comment]
@huri000 Amazing, Thank You! 🙏 😊

**Comment by huri000** [comment]
Hi @Lweek! `0.8.9` will contain the requested feature and be released later today. 
Any preset image will be able to be animated using image-sequence and transformation. The animation repeats itself until the entry is no longer displayed. 
The example project contains an appropriate example (Notes/4).

![Untitled](https://user-images.githubusercontent.com/5504255/54443345-17439300-4749-11e9-9238-b2aa7e22c105.gif)

**Comment by huri000** [comment]
`0.8.9` released.
Let me know if that works for you.
Cheers! 🎉
