### ISSUE TITLE
SwiftEntryKit.dismiss completion handler not called

### ISSUE THREAD

**Issue by riverbaymark** [huri000/SwiftEntryKit#163]
**Describe the bug**
Completion block after dismiss not being called.

**To Reproduce**

SwiftEntryKit.dismiss {
           //Call another function after dismissing the view controller.  Here is my example
           self.grabNPIRelatedInfo()
            
        }

**Expected behavior**
After dismissing the Entry, the function will be called.

**Screenshots**

**iPhone (please complete the following information):**
 - iOS Version: [12.1]
 - Xcode Version [e.g.10.1]
 - Dependency Manager Version [Carthage 0.32.0]
 - SwiftEntryKit Release [# 0.8.8]

**Additional context**
So I am displaying an entry that is a custom nib that has a textfield that the user will input an identification number.  Upon entering this and tapping a submit button on the nib, the entry should dismiss and then call an embedded oauth screen.  This really needs to happen after complete dismissal of the entry, otherwise it tries to present the flow screens on the entry instead of the navigation controller.  

**Screenshots / Video Links**

**Comment by huri000** [comment]
Hi @riverbaymark,
Apologies, but I'm afraid I don't quite understand your problem. 
Doesn't the completion handler get called once the entry is being dismissed? Or is the timing of the completion invocation is the issue perhaps?
Could you attach an example project that shows this particular problem?

Using the [lifecycle events](https://github.com/huri000/SwiftEntryKit#lifecycle-events) of the entry is more encouraged than using `SwiftEntryKit.dismiss`. 
Specifically:
```Swift
attributes.lifecycleEvents.didDisappear = {
// Called after dismissal
}
```

**Comment by riverbaymark** [comment]
Hi @huri000 thanks for the reply.  The completion handler isn't getting called, but the biggest issue is the timing of my OAuth stuff jumping the gun so to speak.  I did a work around by adding a half second delay after just a normal SwiftEntryKit.dismiss and it fixed the issue.  Thanks for the snippet above, I will try that!

Also your library is totally amazing!  It has allowed me to introduce some really cool interfaces for my applications.  I'm a huge fan and just want to say thank you for all the awesomeness!

**Comment by huri000** [comment]
Sure thing! I appreciate it! :-)

Though it worries me that the completion handler doesn't get called as it absolutely must be invoked.
I tried to reproduce this scenario using the example project (by adding a completion handler to the dismiss method called by the sign up form) unsuccessfully.

<img width="785" alt="Screen Shot 2019-03-09 at 10 33 08 PM" src="https://user-images.githubusercontent.com/5504255/54077090-7f632680-42bc-11e9-8eef-278f72382700.png">

If you are able to provide a small example project which reproduces this (view and attributes) you'll do me quite a service :-)

**Comment by huri000** [comment]
A possible explanation for this - It's possible that somehow the dismissal method is overridden with `nil` or another method. That can happen in the case that `dismiss` is called without a handler right after it was called with a handler.
Therefore, the best practice is to utilize the lifecycle events as there can be only one completion handler to `SwiftEntryKit.dismiss` while the lifecycle events are registered as per entry so nothing can nullify them.

Please let me know if that works for you.

**Comment by riverbaymark** [comment]
Thanks @huri000!  Here is a snippet of what I was trying to do:

entryView1.callback = ({[weak self] npi in

            print (npi)
            self!.currentNPI = npi
            
            //Dismisses the Entry but does not complete the block code
            SwiftEntryKit.dismiss {

                //this calls a function that starts the OAuth process
                self!.grabNPIRelatedInfo()
            }

            })

So its called within a completion handler itself.

Mark

**Comment by huri000** [comment]
As I said before, it is much better to "grab" those values in the `willDisappear` lifecycle closure of the entry, as `dismiss` can be replaced by the next entry (since there can be only one `dismiss`).

It seems I could not reproduce this issue using the given info.
Let me know if the suggested solution works for you.
