### ISSUE TITLE
about attributes usage

### ISSUE THREAD

**Issue by whyAreYouSoShy** [huri000/SwiftEntryKit#170]
When I select attributes.position = .bottom, my customView has a gap between the bottom and the attributes. This is not what I want. What should I do in a situation like this .  My English is poor -_-￼￼
`var attributes = EKAttributes.bottomFloat
        attributes.windowLevel = .normal
        attributes.entryBackground = .color(color: .white)
        attributes.screenBackground = .color(color: hexColor(0x000000, 0.5))
        attributes.entranceAnimation = .translation
        attributes.exitAnimation = .translation
        attributes.displayDuration = .infinity
        attributes.positionConstraints.size = .init(width: .constant(value: SCREEN_WIDTH), height: .constant(value: 200))
        attributes.position = .bottom
        
        let customView = UIView()
        customView.backgroundColor = .black
        customView.layer.cornerRadius = 5
        customView.clipsToBounds = true
        let label = UILabel(frame: CGRect(x: 0, y: 170, width: 200, height: 30))
        label.text = "asldfjlksadjsdklfjlk"
        label.font = UIFont.boldSystemFont(ofSize: 30)
        label.textColor = .blue
        customView.addSubview(label)
        SwiftEntryKit.display(entry: customView, using: attributes)`

**Comment by whyAreYouSoShy** [comment]
I find it

**Comment by barrylachapelle** [comment]
Might be helpful to know how you fixed it ;)
