### ISSUE TITLE
Unable to dismiss a ViewControllerEntry in Xcode 10.2 (work in Xcode 10.1)

### ISSUE THREAD

**Issue by RemiRodrigues** [huri000/SwiftEntryKit#171]
**Describe the bug**
Unable to dismiss a ViewControllerEntry by a "screenInteraction" in Xcode 10.2. However, it works in Xcode 10.1.

**To Reproduce**
1. Open a ViewControllerEntry
2. Click outside the entry (screenInteraction)
3. Even if the screenInteraction is set to .dismiss, the behavior works like a .forward

**Expected behavior**
When I click outside the entry, I would like to dismiss the entry.
To do this, I set : 
`attributes.screenInteraction = .dismiss`

**Configuration**
 - iPhone X, iPhone XS, iPhone XR on Simulator 
 - iOS 12.x.x
 - Xcode Version 10.2
 - SwiftEntryKit 0.8.6 and SwiftEntryKit 0.8.9

**Additional context**
My configuration works perfectly on Xcode 10.1, and bug in Xcode 10.2

Thanks in advance,

Rémi Rodrigues,

**Comment by huri000** [comment]
Hi, @RemiRodrigues,
I've just installed `Xcode 10.2`. Running the example project using `SwiftEntryKit` version `0.8.9` I couldn't reproduce your issue. I am trying various presets. Navigation Flow (First item, last section), for example, is a view controller. Tapping it doesn't invoke any unexpected result.
Could you upload a sample project that reproduces this?

**Comment by RemiRodrigues** [comment]
Hello Daniel,

It seems you're right, I have another project using SwiftEntryKit, and it work well using Xcode 10.2.
Sorry for inconvenience.

However, my current project work well using Xcode 10.1, but not using Xcode 10.2.

the bug seems come from my project, but I would like share with you the workaround I found.

In the file `EKAttributes.UserInteraction`, I change this : 
```
var isResponsive: Bool {
   switch defaultAction {
   case .forward:
      return false
   default:
      return true
   }
}
```

Into this :
```
var isResponsive: Bool {
   switch defaultAction {
   case .forward:
      return true
   default:
      return false
   }
}
```

I don't know all the consequences, I always set ScreenInteraction as .dismiss, but now my project work well.

Have a good day :)

**Comment by sorenzi** [comment]
I'm seeing the same issue on Xcode 10.2, dismissing an entry stoped working

**Comment by huri000** [comment]
@sorenzi, think you could send over a sample that demonstrates the issue? As I wrote above, I couldn't reproduce it using my projects or the example project.

**Comment by sorenzi** [comment]
@huri000 this is what I use for most of the views I display in my app

class func attributes() -> EKAttributes {
        var attributes: EKAttributes
        attributes = .bottomNote
        attributes.screenBackground = .color(color: UIColor.black.withAlphaComponent(0.8))
        attributes.displayDuration = .infinity
        attributes.screenInteraction = .dismiss
        attributes.entryBackground = .color(color: .white)
        attributes.statusBar = .dark
        return attributes
    }

**Comment by sorenzi** [comment]
@huri000 I tried right now with your sample app and everything seems to be working, I'm not sure what is different with my app

**Comment by sorenzi** [comment]
Changing var isResponsive: Bool like @RemiRodrigues suggested didnt work for me
I've tested SwiftEntryKit 0.8.8 and 1.0.0

**Comment by huri000** [comment]
May I suggest that you try deintegraing the pods in your project and
reinstall them.

If you can, please send me a reproduceable example inside a project,
something that I can run. That preset configuration hasn’t worked for me.

**Comment by huri000** [comment]
@RemiRodrigues, @sorenzi, B.T.W, What's the **target**'s Swift version? 
In the past, multiple issues were reported in projects that use **Swift 4** and SwiftEntryKit **0.8.1** or above.

**Comment by RemiRodrigues** [comment]
Hi @huri000,

I'm using `Swift 4.2` with `SwiftEntryKit 0.8.6 and 0.8.9`

**Comment by jangsy7883** [comment]
I have the same problem.

But it works fine in debug.

I have problems building with release.

**Debug**
`print(UserInteraction.absorbTouches.isResponsive) //"true"`

**Release**
`print(UserInteraction.absorbTouches.isResponsive) //"false"`

I am using Xcode 10.2, SwiftEntryKit 1.0.0, and Swift 5.

**Comment by sorenzi** [comment]
@huri000 I'm using swift 4.2 SwiftEntryKit 1.0.0

**Comment by huri000** [comment]
Managed to reproduce this thanks to @jangsy7883, and to the consistent weirdness of the Swift compiler. I'll file an issue with Apple since it is definitely a compiler issue, but I should also be able to resolve this by changing the internal code. I'll keep you all posted as soon as possible.

**Comment by huri000** [comment]
@RemiRodrigues @sorenzi @jangsy7883, can you confirm that work properly by using:
`pod 'SwiftEntryKit', :git => 'https://github.com/huri000/SwiftEntryKit.git', :branch => 'bugfix/xcode-10.2-compiler'` in your pod file to pull that fix?
Once confirmed, I'll release `1.0.1`.

**Comment by jangsy7883** [comment]
I have not been solved yet.

**Comment by huri000** [comment]
@jangsy7883 - Forgot to mention, you should `pod deintegrate` before `pod install`ing to remove dependencies. Please let me know if `1.0.1` works for you.

**Comment by RemiRodrigues** [comment]
Hi Daniel,

I confirm you that your fix works fine !

Thanks for your reactivity

**Comment by jangsy7883** [comment]
The problem has been resolved. Thank you!!

**Comment by huri000** [comment]
You're welcome!
SwiftEntryKit `1.0.1` has been released just now and contains that fix. 🎉

**Comment by sorenzi** [comment]
Thanks @huri000 for the prompt fix and incredible library!
