### ISSUE TITLE
Release Events in the environment can be clicked repeatedly

### ISSUE THREAD

**Issue by TonyGJJ** [huri000/SwiftEntryKit#174]
Release in the environment can be clicked repeatedly But Debug is Ok

This My Code And Class
var attributes: EKAttributes {
        // Preset II
        var attributes = EKAttributes.bottomToast
        attributes.windowLevel = .normal
        attributes.displayDuration = .infinity
        attributes.hapticFeedbackType = .success
        attributes.screenBackground = .visualEffect(style: UIBlurEffect.Style.dark)
        attributes.entryBackground = .clear
        attributes.screenInteraction = .dismiss
        attributes.entryInteraction = .absorbTouches
        attributes.entranceAnimation = .init(translate: .init(duration: 0.65, spring: .init(damping: 1, initialVelocity: 0)))
        attributes.exitAnimation = .init(translate: .init(duration: 0.65, spring: .init(damping: 1, initialVelocity: 0)))
        attributes.popBehavior = .animated(animation: .init(translate: .init(duration: 0.65, spring: .init(damping: 1, initialVelocity: 0))))
        attributes.positionConstraints.verticalOffset = 10
        attributes.positionConstraints.size = .init(width: .offset(value: 20), height: .constant(value: 180))
        attributes.positionConstraints.maxSize = .init(width: .constant(value: UIScreen.main.minEdge), height: .intrinsic)
        attributes.statusBar = .light
        return attributes
    }

@IBAction func headBtnAction(_ sender: Any) {
        let view = SelectedPhotoView()
        
        view.cancelBtn.addTarget(self, action:#selector(cancelAction), for: .touchUpInside)
        view.photoBtn.addTarget(self, action: #selector(photoAction), for: .touchUpInside)
        view.cameraBtn.addTarget(self, action: #selector(cameraAction), for: .touchUpInside)
        SwiftEntryKit.display(entry: view,
                              using: attributes)
    }

This My Class
[归档.zip](https://github.com/huri000/SwiftEntryKit/files/3041766/default.zip)

This Release Video
[IMG_1158.MOV.zip](https://github.com/huri000/SwiftEntryKit/files/3041770/IMG_1158.MOV.zip)

This Debug Video
[debug.zip](https://github.com/huri000/SwiftEntryKit/files/3041832/debug.zip)

Thank`s brother

**Comment by huri000** [comment]
Hi @TonyGJJ, what's the Xcode, Swift, SwiftEntryKit version? 
I suspect a duplicated of #171. Please check it out.
If it is, please use SwiftEntryKit `1.0.1`, `pod deintegrate` and then `pod install`.

Let me know your thoughts.

**Comment by qinqi777** [comment]
I face the same problem. when using simulator or run with Xcode in iPhone, there is no problem. But after archive an ipa file, the problem will happen.
set this property: attributes.entryInteraction = .absorbTouches
not work.
In Xcode 10.2, Swift 5.0

**Comment by TonyGJJ** [comment]
@huri000 Thank`s It's solved

**Comment by NunoAlexandre** [comment]
@huri000 I have the same issue but I can't yet upgrade to SwiftEntryKit 1.0.1 as you suggest. Do you have any other suggestion for outdated users?
