### ISSUE TITLE
Build Issue for Dependencies

### ISSUE THREAD

**Issue by ppbpdx** [huri000/SwiftEntryKit#175]
**Describe the bug**
The example project fails to build because of a swift version issue.
Using xcode Version 10.1 (10B61)

**To Reproduce**
1. clone the repo using  'git clone https://github.com/huri000/SwiftEntryKit.git'
2. run 'carthage update'

**Expected behavior**
The build should compile and run however both when trying it in xcode and when running carthage it complains about the swift version and I am unclear on how to correct this.

**Error after running 'carthage upate':**
carthage update
*** Cloning QuickLayout
*** Checking out QuickLayout at "3.0.0"
*** xcodebuild output can be found in /var/folders/4g/fhp6d2_x62g7l4wnntmwr5ph0000gn/T/carthage-xcodebuild.8NcXIB.log
*** Building scheme "QuickLayout" in QuickLayout.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/p/SwiftEntryKit/Carthage/Checkouts/QuickLayout/Example/QuickLayout.xcworkspace -scheme QuickLayout -configuration Release -derivedDataPath /Users/p/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/QuickLayout/3.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/4g/fhp6d2_x62g7l4wnntmwr5ph0000gn/T/QuickLayout SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/p/SwiftEntryKit/Carthage/Checkouts/QuickLayout)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/4g/fhp6d2_x62g7l4wnntmwr5ph0000gn/T/carthage-xcodebuild.8NcXIB.log

**The log file generated shows:**

QuickLayout/3.0.0

Build settings from command line:
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY =
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos12.1
    SKIP_INSTALL = YES
    STRIP_INSTALLED_PRODUCT = NO

Prepare build
note: Using legacy build system

=== BUILD TARGET QuickLayout OF PROJECT QuickLayout WITH CONFIGURATION Release ===

Check dependencies
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.

** ARCHIVE FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

Likewise in xcode the following error appears see attached. I am sure this is my error but if you could advise on how to fix I would very much appreciate it.
<img width="577" alt="Screen Shot 2019-04-04 at 10 45 40 PM" src="https://user-images.githubusercontent.com/5177162/55605907-96662e80-572b-11e9-92c8-3f41687d73c9.png">

**Comment by huri000** [comment]
Hi @ppbpdx, That makes sense as the example project is configured to work with Xcode 10.2, Swift 5.
You used Xcode 10.1... 
You can set Git HEAD to `0.8.9` tag and run it again. It'll work properly.

**Comment by ppbpdx** [comment]
You are the best! That worked, sorry I need to move to 5... soon.
