### ISSUE TITLE
Date/Time picker support in the Forms

### ISSUE THREAD

**Issue by agonzalezjr** [huri000/SwiftEntryKit#181]
First of: great job! This is an amazing library!

It would be great to have a way to be able to add Date/Time picker to the Forms. Once the field is selected, the row is expanded showing the picker. Like in this mock up:

![Simulator Screen Shot - iPhone Xs - 2019-04-30 at 11 29 55](https://user-images.githubusercontent.com/8965941/56973985-f50ca580-6b3b-11e9-9387-24a2d7bdd12a.png)

Is this something that is already planned or in there already and I haven't been able to find how to do it?

**Comment by agonzalezjr** [comment]
Ok ... I think I could achieve this using a custom view 😉

**Comment by agonzalezjr** [comment]
Another thing I tried in a local fork was the ability to provide a custom `inputView` for the TextViews in the Form Entries and set the date picker (or whatever there). It also required adding a method to be able to set TextView values as well, but it worked pretty well! 

Is this something you would be interested in adding support for with a PR?

**Comment by huri000** [comment]
Hi @agonzalezjr! The `inputView` approach is better than manually hardcoding everything into the forms, IMHO. 
That way developers may be able to manually define their custom input views, while the form preset parse and translate strings between the `inputView` and the eventual output.

Unfortunately, I'm a bit short in time, but you are very much welcome to PR your forked code if you want. If you are, please take a look at [this](https://github.com/huri000/SwiftEntryKit/blob/master/CONTRIBUTING.md) before your PR.

Let me know your thoughts. :-)
Cheers!

**Comment by huri000** [comment]
Closing. Not sure this is needed as a preset inside the base library.
