### ISSUE TITLE
Edit currently displaying view

### ISSUE THREAD

**Issue by albert102000** [huri000/SwiftEntryKit#183]
I'm trying to edit the label or button text on my form. This is how I am displaying it: 

`    func showSignupForm() {
     var attributes: EKAttributes
    
    attributes = .float
    attributes.windowLevel = .normal
    attributes.position = .center
    attributes.displayDuration = .infinity
    
    attributes.entranceAnimation = .init(translate: .init(duration: 0.65, anchorPosition: .bottom,  spring: .init(damping: 1, initialVelocity: 0)))
    attributes.exitAnimation = .init(translate: .init(duration: 0.65, anchorPosition: .top, spring: .init(damping: 1, initialVelocity: 0)))
    attributes.popBehavior = .animated(animation: .init(translate: .init(duration: 0.65, spring: .init(damping: 1, initialVelocity: 0))))
    
    attributes.entryInteraction = .absorbTouches
    attributes.screenInteraction = .dismiss
    
    attributes.entryBackground = .color(color: .white)
    attributes.screenBackground = .color(color: .dimmedDarkBackground)
    
    attributes.border = .value(color: UIColor(white: 0.6, alpha: 1), width: 1)
    attributes.shadow = .active(with: .init(color: .black, opacity: 0.3, radius: 3))
    attributes.scroll = .enabled(swipeable: false, pullbackAnimation: .jolt)
    attributes.statusBar = .light
    
    attributes.positionConstraints.keyboardRelation = .bind(offset: .init(bottom: 15, screenEdgeResistance: 0))
    attributes.positionConstraints.maxSize = .init(width: .constant(value: UIScreen.main.minEdge), height: .intrinsic)
    
    let style = FormStyle.light
    
    let title = EKProperty.LabelContent(text: "Fill your personal details", style: style.title)
    let textFields = FormFieldPresetFactory.fields(by: [.fullName, .mobile, .email, .password], style: style)
    var button = EKProperty.ButtonContent(label: .init(text: "Continue", style: style.buttonTitle), backgroundColor: appRed, highlightedBackgroundColor: style.buttonBackground.withAlphaComponent(0.8))
    button.action = {
        let name = textFields[0].textContent
        let mobile = textFields[1].textContent
        let email = textFields[2].textContent
        let password = textFields[3].textContent
        if (name.count > 0 && mobile.count > 0 && email.count > 0 && password.count > 0) {
            SwiftEntryKit.dismiss()
        } else {
            //ADD CODE HERE
        }
    }
    let contentView = EKFormMessageView(with: title, textFieldsContent: textFields, buttonContent: button)
    attributes.lifecycleEvents.didAppear = {
        contentView.becomeFirstResponder(with: 0)
    }
    SwiftEntryKit.display(entry: contentView, using: attributes, presentInsideKeyWindow: true)
}`

The use case is that I want to notify the user that he must fill in all of the fields, the email format isn't correct etc - however I'm not sure how to edit the currently displaying item to change the title or button text. The closest I've come is creating a new view and transforming using the `SwiftDisplayKit.transform` func, but this is less than ideal.

**Comment by huri000** [comment]
Hi @albert102000,

What you are trying to accomplish is not possible at the moment using `SwiftEntryKit`.
However, this is definitely on the project's roadmap.

I would appreciate if you could elaborate on your suggestion a bit more.
I understand you are trying to verify the "correctness" of the user input.
Additionally, you also wish to show a textual hint as to the incorrect input in order to help the user to satisfy the form's requirements.

As to the change of the inner content inside the entries, there is a similar open issue - #100. 
So, I'm closing that one. Please elaborate everything inside #100.

**Comment by zjohnzheng** [comment]
Hey, just a comment, I've been able to do this using delegates and protocols.
