### ISSUE TITLE
Handling a UILongPressGestureRecognizer for button entry

### ISSUE THREAD

**Issue by HowardTheDuck007** [huri000/SwiftEntryKit#185]
Hi Daniel, what a great library! :-)
Is there any way to handle a long pressure for an entry button. I am using a button with long-press to record an audio track, and would love to handle it within a pop-up...Thank you!

**Comment by huri000** [comment]
Hi @HowardTheDuck007,
This is not possible at the moment, but may be a good idea to add such capability.

**Comment by HowardTheDuck007** [comment]
> Hi @HowardTheDuck007,
> This is not possible at the moment, but may be a good idea to add such capability.

Hi Daniel, thank you. In the meanwhile I guess the only option is to use a custom view. I tried to implement one....not sure if it was my mistake (probably) or if it is a sort of incompatibility, but if I try to load a custom view on top of a Scenekit view (of course in the parent view) the actual parameters are not allowing the view to appear ). And if I just add a view skipping SwiftEntryKit that view appears with completely wrong positioning (I believe due to the indeed different positioning of coordinates in SceneKit)...Just thought to drop you this note in case in the future you want to check that option as well. Thank you again for the library!

**Comment by huri000** [comment]
Apologies, but I don't have the time capacity to implement that feature. Closing but feel free to open a PR for me to review.
