### ISSUE TITLE
Could not build Objective-C module 'SwiftEntryKit'

### ISSUE THREAD

**Issue by UAEpro** [huri000/SwiftEntryKit#186]
**Describe the bug**
i have problem, i got this error while building
`Could not build Objective-C module 'SwiftEntryKit'`

**iPhone (please complete the following information):**
 - iPhone X
 - iOS Version: iOS 11.1.3
 - Xcode Version 10.2
 - Dependency Manager Version CocoaPods 1.5.2
 - SwiftEntryKit Release  1.0.1
 - Swift: 5

**Comment by huri000** [comment]
Hi @UAEpro, 
What are you trying to build exactly (example project, your own project)?
I don't have enough info, but it might be a caching issue. Please follow these [steps].(https://github.com/huri000/SwiftEntryKit/issues/138#issuecomment-438986841)

**Comment by UAEpro** [comment]
the problem was because of using older compiler, (thought project was on swift 5)
After changing to swift 5 and then re installing pods everything seems to work fine
