### ISSUE TITLE
Subviews outside of custom view bounds

### ISSUE THREAD

**Issue by barrylachapelle** [huri000/SwiftEntryKit#189]
Hello thanks for the awesome lib.

I have been trying to have a subview in my custom view bleed outside of the bounds. I am not sure - but it feels like the library is using clipsToBounds somewhere that will not allow for this.

So far I have tried setting clipsToBounds = false for my custom view, paddling the custom view with UIEdgeInsets. No luck. Am I missing something?

In the image below I am trying to have their heads visible outside the custom view panel. Thanks

<img width="399" alt="Screen Shot 2019-05-28 at 4 46 19 PM" src="https://user-images.githubusercontent.com/1087169/58511415-c698df00-8168-11e9-99a8-1f806eaf2a08.png">

```
        //show success panel
        var attributes = EKAttributes.bottomFloat
        attributes.hapticFeedbackType = .success
        attributes.windowLevel = .normal
        attributes.positionConstraints.verticalOffset = -48
        attributes.screenBackground = .color(color: colorDarkTransparent)
        attributes.displayDuration = 3.0
        attributes.positionConstraints.size = .init(width: .constant(value: screenSize.width), height: .constant(value: 600))
        attributes.entranceAnimation = .init(translate: .init(duration: 0.48, anchorPosition: .bottom,  spring: .init(damping: 1, initialVelocity: 0)))
        attributes.exitAnimation = .init(translate: .init(duration: 0.48, anchorPosition: .bottom, spring: .init(damping: 1, initialVelocity: 0)))
        
        //custom view
        let signUpSuccessView = UIView()
        //signUpSuccessView.frame = CGRect(x: 0, y: 100, width: screenSize.width, height: 400)
        signUpSuccessView.layoutMargins = UIEdgeInsets(top: -8, left: 8, bottom: 8, right: 8)
        signUpSuccessView.backgroundColor = .white
        signUpSuccessView.layer.cornerRadius = 24
        signUpSuccessView.clipsToBounds = false
        

        //family image
        let familyImageView = UIImageView()
        familyImageView.frame = CGRect(x: 0, y: -40, width: screenSize.width, height: 280)
        familyImageView.image = UIImage(named: "Family")
        familyImageView.contentMode = UIView.ContentMode.scaleAspectFit
        familyImageView.clipsToBounds = false
        familyImageView.layer.masksToBounds = false;
        signUpSuccessView.addSubview(familyImageView)

```

**Comment by barrylachapelle** [comment]
Actually please disregard this. I ended up making my custom view full screen height with a transparent background and then drawing all the components in Swift. Thank you.

<img width="305" alt="Screen Shot 2019-05-30 at 8 39 04 AM" src="https://user-images.githubusercontent.com/1087169/58633450-7d56a580-82b6-11e9-885b-e73cad1f4363.png">

**Comment by huri000** [comment]
Hi @barrylachapelle! Every entry is embedded within another view which clips all subviews to its bounds. That's just how things are built in this library.
I'm was aware of this consequence when I first made this, but now it may seem like a good idea to reconsider.

**Comment by barrylachapelle** [comment]
It might be easy to have an attribute for toggling clipping. Not sure if this has ever come up before.

**Comment by Jayxiang** [comment]
+1
