### ISSUE TITLE
No such module "QuickLayout" in sample project.

### ISSUE THREAD

**Issue by Rogho** [huri000/SwiftEntryKit#193]
**Describe the bug**

Downloaded sample project of latest version, tried to compile it, it gave me error -  No such module "QuickLayout" in sample project.

**Comment by Hamza-Almass** [comment]
hello , 

yes also i am download the project ,it gave me error - No such module "QuickLayout" in sample project.

**Comment by huri000** [comment]
Hi @Rogho, @Hamza-Almass,

Please note that there is a closed issue referencing that.
See #54 and #31 for additional information.

In case you followed the README installation instructions, and the troubleshooting info in #31 and couldn't install the example project, please let me know. 

I'm closing this for the moment for the reason above.
