### ISSUE TITLE
Display Entry throughout the entire of the App

### ISSUE THREAD

**Issue by mojtaba-almoussawi** [huri000/SwiftEntryKit#200]
I need to display an entry throughout the entire of the App, (off course sometimes i need to dismiss it and display it again) but for most of the viewController i need some entry to be always displayed with ability to navigate through the App, 

If i set the screenInteraction : `attributes.screenInteraction = .absorbTouches`
I can't then touch any other view.

**Comment by huri000** [comment]
What about `.forward`?
[read here](https://github.com/huri000/SwiftEntryKit#user-interaction).

**Comment by huri000** [comment]
Closing this issue, assuming you worked it out using the tip above.
