### ISSUE TITLE
Error StatusBarHidden & StatusBarStyle

### ISSUE THREAD

**Issue by devLoop1** [huri000/SwiftEntryKit#201]
Hello, install through cocoapods and when starting the project shows me the error that is seen in the attached image.
I hope they can help me.

Xcode 10.2.1
Swift 5

<img width="1270" alt="Captura de Pantalla 2019-06-24 a la(s) 14 28 13" src="https://user-images.githubusercontent.com/48538624/60042868-b521f480-968c-11e9-996b-4ee0dcdc6b7d.png">

**Comment by huri000** [comment]
Please see [this](https://github.com/huri000/SwiftEntryKit/issues/161). 
tl;dr lots of devs still manually set the status bar.
Closing.
