### ISSUE TITLE
How to add validation to FormFieldPresetFactory.fields 

### ISSUE THREAD

**Issue by arishanapalli** [huri000/SwiftEntryKit#204]
How to add the validation for the textfields and access those valid value from it.

let textFields = FormFieldPresetFactory.fields(by: [.email], style: style)
I assume textFields.text shows the enter text value inside the textfields.
How to access those value from the FormFieldPresetFactory.fields (with given parameters)

**Comment by huri000** [comment]
There is no way to do this (at the moment) using the `SwiftEntryKit`'s presets, so until it's implemented, you will have to use your own custom entry view.

**Comment by huri000** [comment]
Closing as it won't be implemented in the intermediate future.
