### ISSUE TITLE
Update attributes once pop up displayed

### ISSUE THREAD

**Issue by bkunarola** [huri000/SwiftEntryKit#207]
How to update attributes for currently displayed pop up.

Suppose I have displayed a pop up with following attribute:

`attributes.positionConstraints.size = .init(width: .fill, height: .ratio(value: 0.6))
SwiftEntryKit.display(entry: TagPopUp(), using: attributes)`

I want to update attributes when keyboard opens and set the attribute as :

`attributes.positionConstraints.size = .init(width: .fill, height: .ratio(value: 1.0))`

Please let me know if this is possible.

**Comment by huri000** [comment]
@bkunarola, `SwiftEntryKit` is not currently supporting this, but there is an open issue #100 that refers to what you're seeking to do.
I'm closing this now but please feel free to append your request as a comment for #100.
