### ISSUE TITLE
EKAttributes#entryBackground doesn't get updated when switching to dark mode

### ISSUE THREAD

**Issue by doodzik** [huri000/SwiftEntryKit#208]
**Describe the bug**

When switching from dark mode to light mode the entryBackground color doesn't get updated.

```swift
attributes.entryBackground = .color(color: .tertiarySystemBackground)
attributes.positionConstraints.safeArea = .empty(fillSafeArea: true)
```

**To Reproduce**
Steps to reproduce the behavior in the simulator:
1. `SwiftEntryKite.display` a view with the configuration provided.
1. Open the settings app and click on developer
2. Click on UISwitch to enable dark mode
3. Open the app again

**Expected behavior**

When switching from dark mode to light mode the entryBackground color should change

**Screenshots**

<img width="451" alt="Screen Shot 2019-07-20 at 15 01 14" src="https://user-images.githubusercontent.com/5946811/61583065-f4fbc080-ab00-11e9-838b-9fe978a0e98e.png">
<img width="456" alt="Screen Shot 2019-07-20 at 15 16 09" src="https://user-images.githubusercontent.com/5946811/61583099-50c64980-ab01-11e9-952f-f53c9040b678.png">

**iPhone (please complete the following information):**
 - Device: iPhone XR Beta Simulator
 - iOS Version: iOS13 Beta
 - Xcode Version: 11.0 beta 
 - Dependency Manager Version: CocoaPods 1.5.2
 - SwiftEntryKit Release # 1.0.1

**Additional context**

I think it has something to do with the CALayer in [EKBackgroundView](https://github.com/huri000/SwiftEntryKit/blob/75d0f45251dd2b4e612c83d5d321f70ed3a00c54/Source/Infra/EKBackgroundView.swift#L67). If you skip the provided video (bottom of the issue) to minute 24 you can see what I mean. I played around with it, but I couldn't find a view that has the correct `traitCollection`.

rest of the configuration
```swift
attributes = .bottomFloat
attributes.displayDuration = .infinity
attributes.screenBackground = .clear
attributes.entryBackground = .color(color: .tertiarySystemBackground)
attributes.screenInteraction = .forward
attributes.entryInteraction = .forward
attributes.scroll = .edgeCrossingDisabled(swipeable: true)
attributes.entranceAnimation = .init(translate: .init(duration: 0.5, spring: .init(damping: 1, initialVelocity: 0)))
attributes.exitAnimation = .init(translate: .init(duration: 0.35))
attributes.popBehavior = .animated(animation: .init(translate: .init(duration: 0.35)))
attributes.positionConstraints.size = .init(width: .fill, height: .intrinsic)
attributes.positionConstraints.verticalOffset = 0
attributes.positionConstraints.safeArea = .empty(fillSafeArea: true)
attributes.shadow = .active(with: .init(color: .systemGray, opacity: 0.3, radius: 6))
```

**Screenshots / Video Links**

Implementing Dark Mode on iOS: https://developer.apple.com/videos/play/wwdc2019/214

**Comment by huri000** [comment]
Thanks, @doodzik. I'll look into it.

**Comment by huri000** [comment]
@doodzik, not sure it's `EKBackgroundView` since it's colored according to what specified in the given `EKAttributes`.
I suspect that maybe your `UIPickerView` is constrained to the bottom safe-area of its superview, thus exposing its white background. I couldn't know for sure. Could you send over a reproducible example project perhaps?

**Comment by huri000** [comment]
btw, thank for pinging on the dark mode subject. soon it's going to be quite important for users.
It seems that for custom entries there is full support on dark-mode because anything can be customized to the extreme, but I'm now preparing built-in support in `SwiftEntryKit` presets.

**Comment by huri000** [comment]
`SwiftEntryKit` now supports dark mode (`1.1.0`).  please read the [changelog](https://github.com/huri000/SwiftEntryKit/blob/master/CHANGELOG.md) to catch up with what should be done to achieve that.
Let me know if you have any questions.

**Comment by doodzik** [comment]
🎉
