### ISSUE TITLE
Enabling Multiple Windows results in SwiftEntryKit Display to do nothing

### ISSUE THREAD

**Issue by Umar-M-Haroon** [huri000/SwiftEntryKit#211]
**Describe the bug**
Enabling Multiple windows on iOS 13 results in no presentation of any view controllers or views via SwiftEntryKit

**To Reproduce**
1. Enable Multiple Windows on iOS 13
2. Implement SceneDelegate and Appdelegate to support multiple windows
3. Display any view controller or view

**Expected behavior**
Displayed Items should show up normally

**Screenshots**
N/A

**iPhone (please complete the following information):**
 - Device: [iPad Air 2, iPhone 7+]
 - iOS Version: [13.0 b4]
 - Xcode Version [11 b4]
 - Dependency Manager Version [CocoaPods 1.7.1]
 - SwiftEntryKit Release # [e.g. 1.1.0]

**Additional context**
The main culprit seems to be how iOS 13 handles windows and window scenes. Removing the whole SceneConfiguration in the info.plist and multiple window option in the plist shows the windows again

**Comment by Umar-M-Haroon** [comment]
Just tried changing the way the window is initialized with super.init(windowScene:) and using the keyWindow.windowScene but no avail. It looks like its the way windows are presented on iOS 13 that changes it

**Comment by huri000** [comment]
Hi, thanks for opening an issue. Unfortunately I don’t have time to dive into SwiftUI compatibility issues. It will definitely help if you send over a reproducible sample project.

**Comment by huri000** [comment]
@Umar-M-Haroon, please check out the change I'm introducing in [this PR](https://github.com/huri000/SwiftEntryKit/pull/212).

I'm not going to merge this for now, but you can fork `SwiftEntryKit` and copy the snippet. 
I want to be sure that there won't be ricochets after this.

It worked well for me with the `.plist` `SwiftUI` configuration.

Please let me know if that works well for you.

**Comment by Umar-M-Haroon** [comment]
I just tried that change out, it seems to work well. I think thats the correct method to handle it as well. I'll close this out as it seems to solve it

**Comment by huri000** [comment]
@Umar-M-Haroon good. thanks for the heads up. please let me about any related issue, so I can investigate and update #213 to be merge-ready by the time Xcode 11 is officially released.

**Comment by Umar-M-Haroon** [comment]
Sounds good, I'll keep you updated. Thanks for all the work you've done!
