### ISSUE TITLE
The frame below the view appears

### ISSUE THREAD

**Issue by shjdunglv** [huri000/SwiftEntryKit#215]
**Describe the bug**
Why can't I turn off this frame? I have loaded Viewcontroller from xib. When I use roundCorners, it does not lose in the corner.

**To Reproduce**
        let edgeWidth = UIScreen.main.bounds.width
        let edgeHeight = UIScreen.main.bounds.height
        attributes.position = .center
        attributes.hapticFeedbackType = .success
        attributes.displayDuration = .infinity
        attributes.entryBackground = .clear
        attributes.screenBackground = .visualEffect(style: .dark)
//        attributes.shadow = .active(with: .init(color: .black, opacity: 0.3, radius: 8))
        attributes.screenInteraction = .absorbTouches
        attributes.entryInteraction = .absorbTouches
        attributes.roundCorners = .all(radius: 50)
        attributes.scroll = .enabled(swipeable: true, pullbackAnimation: .jolt)
        attributes.entranceAnimation = .init(translate: .init(duration: 0.7, spring: .init(damping: 0.7, initialVelocity: 0)),
                                             scale: .init(from: 0.7, to: 1, duration: 0.4, spring: .init(damping: 1, initialVelocity: 0)))
        attributes.exitAnimation = .init(translate: .init(duration: 0.2))
        attributes.popBehavior = .animated(animation: .init(translate: .init(duration: 0.35)))
        attributes.positionConstraints.size = .init(width: .offset(value: 20), height: .constant(value: 300))
        attributes.positionConstraints.maxSize = .init(width: .constant(value: edgeWidth), height: .constant(value: edgeHeight))
        attributes.statusBar = .dark

**Screenshots**
![IMG_0001](https://user-images.githubusercontent.com/29003675/62103867-bd4b0080-b2d8-11e9-84b2-93e4f1ec83eb.PNG)

**iPhone (please complete the following information):**
 - Device: Iiphone 6S
 - iOS Version: 12.3.1
 - Xcode Version 10.1
 - SwiftEntryKit Release 0.7.2

**Comment by huri000** [comment]
The attributes seem correct, but I cannot estimate what's wrong from that code alone. 
Could you upload a project that shows the issue?

A wild estimation - something is wrong in the custom view layout (maybe you didn't use auto-layout)?

**Comment by shjdunglv** [comment]
Hi Huri000. Thank you for reply!
I have found the reason. Because I inherited the BaseView class and set the background to BaseView.
![image](https://user-images.githubusercontent.com/29003675/62120535-bafa9d80-b2fc-11e9-94c4-54a2d4feffc7.png)
Thanks you very much. Sorry for my english not being good.
