### ISSUE TITLE
How to change view size during displaying

### ISSUE THREAD

**Issue by CoderMaurice** [huri000/SwiftEntryKit#217]
I tried to change positionConstraints in Attributes but it didn't work

**Comment by huri000** [comment]
Please be more specific describe the issue in details, provide attributes and view, and a sample project if possible.

**Comment by CoderMaurice** [comment]
For example, white view's size is  (300, 500)
```
EKAttributes.positionConstraints.size.width = .constant(value:300)
EKAattributes.positionConstraints.size.height = .constant(value:500)
```
After SwiftEntryKit.display this view 
How to change view size to  (300, 200)

![image](https://user-images.githubusercontent.com/22311615/62359828-2d13f200-b54a-11e9-8e9e-906c681d2854.png)
![image](https://user-images.githubusercontent.com/22311615/62359841-3309d300-b54a-11e9-88c0-bb5f5646edc9.png)

**Comment by huri000** [comment]
Could you please zip a side project and send over? There is not enough info here for me to provide help.

**Comment by CoderMaurice** [comment]
sry, i think i can't use project to describe this problem, its actually a simple question, maybe I didn’t express it clearly.
What I think is that when I click the continue button, change the height of this view,

![image](https://user-images.githubusercontent.com/22311615/62360677-f50dae80-b54b-11e9-9db5-1ddc229b26cb.png)

**Comment by CoderMaurice** [comment]
blue part is original size 
after click continue button
view size change to red
How can i do this
![image](https://user-images.githubusercontent.com/22311615/62361050-c3e1ae00-b54c-11e9-942f-39c6183f0fe2.png)

**Comment by huri000** [comment]
That’s not possible at the moment.
Actually there is an open issue for that #176. You are welcome to endorse it by thumbing it up.

**Comment by CoderMaurice** [comment]
thanks 
SwiftEntryKit is a great project!!!
