### ISSUE TITLE
Cannot locate buttons for UI tests

### ISSUE THREAD

**Issue by alexcurylo** [huri000/SwiftEntryKit#222]
**Describe the bug**

SwiftEntryKit dialogs cannot be recorded in UI tests

**To Reproduce**

1. Record a UI test with Xcode
2. Tap a SwiftEntryKit button
3. Recording aborts with an error that no control could be found

However, it turns out that if we do script access to labels and buttons it'll work, so this is just somewhat of an inconvenience. But exposing `accessibilityIdentifier` would be a nice feature to add!

**Expected behavior**

Ideally, the `accessibilityIdentifier` should be settable in title, button, etc. attributes so we can script tests that don't depend on translations.

**Screenshots**

**iPhone (please complete the following information):**
 - Device: All
 - iOS Version: All
 - Xcode Version: 10.3
 - Dependency Manager Version: CocoaPods 1.7.5
 - SwiftEntryKit Release # 1.1.2

**Additional context**

**Screenshots / Video Links**

**Comment by huri000** [comment]
Accessibility is supported for buttons as well (release 1.2.5), and some fine tunes were made. Please see the changes under the changelog file.
