### ISSUE TITLE
Description label custom content layout 

### ISSUE THREAD

**Issue by iWeslie** [huri000/SwiftEntryKit#224]
**Is your feature request related to a problem? Please describe.**
I cannot customize description label content offset. When I use EK as the DEBUG logger, sometimes the log info will be lengthy and the content offset is not good-look.

Here is the log info.
<img width="545" alt="Screen Shot 2019-08-23 at 6 36 20 PM" src="https://user-images.githubusercontent.com/12584632/63587370-6d5d1200-c5d6-11e9-9e31-a98676dd7835.png">

As you can see the description is long, so I wanna I can stretch it to the left margin and fit the blue box as well.

<img width="378" alt="Screen Shot 2019-08-23 at 6 39 08 PM" src="https://user-images.githubusercontent.com/12584632/63587386-78b03d80-c5d6-11e9-8719-71db749ae894.png">

But I found that these two labels are in a container view and there is a constraint between the image and container view, so it will be a little hard to remake constraint to reach my purpose.

**Describe the solution you'd like**
So, I will be very appreciated if you could add this feature to customize the layout.

**Comment by huri000** [comment]
Unfortunately, I don't have time to look into this. Closing, but feel free to open a PR for me to look at if you want.
