### ISSUE TITLE
Xcode 11.0 beta6 BUILD FAILED

### ISSUE THREAD

**Issue by iWeslie** [huri000/SwiftEntryKit#225]
Xcode Version:
Version 11.0 beta 6 (11M392q)

The error is odd.
<img width="1253" alt="Screen Shot 2019-08-24 at 5 12 18 PM" src="https://user-images.githubusercontent.com/12584632/63635197-63004e00-c692-11e9-8aa2-586eeb5370ea.png">

**Comment by huri000** [comment]
Just do [some cleanup](https://github.com/huri000/SwiftEntryKit/issues/219#issuecomment-520705548). It does not seem like a library bug to me.

**Comment by iWeslie** [comment]
Unfortunately, I've tried your suggestion but it didn't work.
As you can see, I used EK in SPM, where something went wrong. But, it works fine with CocoaPods. 
This project is new and I ONLY add `Alamofire` and `SwiftEntryKit` from 
> Xcode11 > File > Swift Packages > Add Package Dependency

AND I ONLY import is as well. I don't think it is some cache issues because the project is a new one and I've ONLY create a vc.

<img width="286" alt="Screen Shot 2019-08-24 at 10 38 28 PM" src="https://user-images.githubusercontent.com/12584632/63638857-ea17eb00-c6bf-11e9-8fd1-e646862c6851.png">


I think you may give it a try to see if it is an issue about SPM. I created a new Single application project, add EK and AF as dependency and this bug reproduced. And my macOS and Xcode are the latest version from dev.apple

Last but not least, if I only add Alamofire from Xcode from SPM, it works fine and everything is okay.

**Comment by huri000** [comment]
Hi, you're right, `SPM` does require importing libs to the relevant files.
I was not aware that you are using `SPM`. For future issues, please state the dependency manager inside the description as described in the guidelines of the project.

I just merged a pending PR #220 (fix) into `master`, and `1.1.3` will be released in the next few minutes.
Once released I'll close this issue. Please let me know if that works for you.

**Comment by iWeslie** [comment]
Well, I'm sorry that I didn't described it clearly. So, I've just checkout the 1.1.3 release and the issue is gone. Thank you so much! 😆Now I don't need to import the freaking xcproj manually or depend on pod as well.

**Comment by huri000** [comment]
Glad I could help. :-)
