### ISSUE TITLE
Clicked continue button in form style, the action is not being called.

### ISSUE THREAD

**Issue by squarezw** [huri000/SwiftEntryKit#229]
**Describe the bug**
When I use the form demo that is the "Center Float in Forms". and I set a breakpoint on `ButtonContent` callback named action, I supposed it will be call when I clicked continue. but no action triggered, even I print some sample words in there.

**To Reproduce**
1. Go to Forms Center Float
2. Click on 'Continue'
3. Set a breakpoint on action callback.
4. No callback is called.

```
 let button = EKProperty.ButtonContent(
            label: .init(text: "Continue", style: style.buttonTitle),
            backgroundColor: style.buttonBackground,
            highlightedBackgroundColor: style.buttonBackground.with(alpha: 0.8),
            displayMode: displayMode,
            accessibilityIdentifier: "continueButton") {
            SwiftEntryKit.dismiss()
}
```

the SwiftEntryKit.dismiss() is not being called, even I print some.

**Comment by huri000** [comment]
Which version of Xcode, SwiftEntryKit and device were you using?

**Comment by alexandermucalov** [comment]
I'm also facing this issue with AlertMessageViews, using Xcode version 10.1, SwiftEntryKit version 1.0.2, and old iPhone SE, version 12.4.1.

**Comment by alexandermucalov** [comment]
(By the way, love the library - so expressive and easy to use.)

**Comment by huri000** [comment]
Thanks! ^^
Unfortunately, I cannot seem to reproduce this with the example project. It was breaking as expected inside the form/alert callback.
<img width="813" alt="Screen Shot 2019-09-15 at 17 40 50" src="https://user-images.githubusercontent.com/5504255/64924803-49a97800-d7e0-11e9-8e48-3941ebb513fd.png">

Further info (even a sample project that reproduces this) would be appreciated.

**Comment by alexandermucalov** [comment]
Scratch my comment - user error (forgot to set attributes.entryInteraction = .absorbTouches). Sorry for raising the issue prematurely, and thanks for taking a look!

**Comment by squarezw** [comment]
Thanks @huri000, It's work now. probably it's my Xcode bugs.
