### ISSUE TITLE
Screen interaction is disabled when status bar entry kit is being displayed

### ISSUE THREAD

**Issue by avjiang** [huri000/SwiftEntryKit#231]
I am having problem where screen interaction is being disabled when the entry kit is displaying. Once the entry kit is dismissed, the screen interaction is enabled again

Xcode 11, iOS 13, iPad application, Swift Entry Kit 1.1.3

here are my codes 

    var attributes = EKAttributes()
        attributes = .statusBar
        attributes.hapticFeedbackType = .success
        attributes.displayDuration = .infinity
        attributes.screenInteraction = .forward
        attributes.popBehavior = .animated(animation: .translation)
        attributes.entryBackground = .color(color: .satCyan)
        attributes.shadow = .active(with: .init(color: .chatMessage, opacity: 0.5, radius: 2))
        attributes.statusBar = .light
        
        let text = "hello world"
        let style = EKProperty.LabelStyle(font: MainFont.light.with(size: 14), color: .white, alignment: .center)
        let labelContent = EKProperty.LabelContent(text: text, style: style)
        let sequence = (1...4).map { "cloud\($0)" }
        let animationDuration: TimeInterval = 1
        let animation = EKProperty.ImageContent.TransformAnimation.animate(duration: animationDuration, options: [.curveEaseInOut], transform: .init(scaleX: 1.1, y: 1.1))
        let imageContent = EKProperty.ImageContent(imagesNames: sequence, imageSequenceAnimationDuration: animationDuration, animation: animation, size: CGSize(width: 20, height: 20), contentMode: .scaleAspectFit)
        
        let contentView = EKImageNoteMessageView(with: labelContent, imageContent: imageContent)
        
        SwiftEntryKit.display(entry: contentView, using: attributes)`

**### UPDATE** 
@huri000 
If the sample project is run in ipad simulator, this problem will appear. Any recommendation on this?

**Comment by dimasno1** [comment]
I have same problem. This issue is relevant for iOS 13

**Comment by huri000** [comment]
I'll be looking into it soon (hopefully today) and keep you posted.

**Comment by huri000** [comment]
I PRd a fix [here](#233). I still wanna test this properly before shipping a new release. Please let me know if that works for you. If it does, I'll be shipping this today.

**Comment by avjiang** [comment]
Hello @huri000 thanks for the reply, How can I test it? Sorry for the stupid question. I am a junior developer and still learning about git. Thanks

**Comment by huri000** [comment]
I don't quite sure if thats the exact pod cmd, but can state something like the following:
`pod 'SwiftEntryKit', :git => 'https://github.com/huri000/SwiftEntryKit.git, :branch => 'fix/issue-231/ipad-screen-interaction`
Cocoapods has pretty good doc on that.

**Comment by avjiang** [comment]
```
 var attributes = EKAttributes()
        attributes = .statusBar
        attributes.hapticFeedbackType = .success
        attributes.screenInteraction = .forward
        attributes.displayDuration = .infinity
        attributes.popBehavior = .animated(animation: .translation)
        attributes.entryBackground = .color(color: .satCyan)
        attributes.shadow = .active(with: .init(color: .chatMessage, opacity: 0.5, radius: 2))
        attributes.statusBar = .hidden
        
        let text = "Synchronization is in progress"
        let style = EKProperty.LabelStyle(font: MainFont.light.with(size: 14), color: .white, alignment: .center)
        let labelContent = EKProperty.LabelContent(text: text, style: style)
        let sequence = (1...4).map { "cloud\($0)" }
        let animationDuration: TimeInterval = 1
        let animation = EKProperty.ImageContent.TransformAnimation.animate(duration: animationDuration, options: [.curveEaseInOut], transform: .init(scaleX: 1.1, y: 1.1))
        let imageContent = EKProperty.ImageContent(imagesNames: sequence, imageSequenceAnimationDuration: animationDuration, animation: animation, size: CGSize(width: 20, height: 20), contentMode: .scaleAspectFit)
        
        let contentView = EKImageNoteMessageView(with: labelContent, imageContent: imageContent)
        
        SwiftEntryKit.display(entry: contentView, using: attributes)
```

and here is my pod 
    
`pod 'SwiftEntryKit', :git => 'https://github.com/huri000/SwiftEntryKit.git', :branch => 'fix/issue-231/ipad-screen-interaction'`
    
The problem still there. Am I doing something wrong?

**Comment by huri000** [comment]
Just released `1.1.4`. Please try that instead.

**Comment by dimasno1** [comment]
> Just released `1.1.4`. Please try that instead.

works fine, thanks

**Comment by avjiang** [comment]
Hmm.. i am still unable to scroll my collectionView when there is status bar entry kit is being displayed. Running it in simulator. Am I missing something?

**Comment by huri000** [comment]
@avjiang please make sure you install the correct version. In any case it would be good to clean your cached pod libraries and reinstall them.

**Comment by avjiang** [comment]
@huri000 now it works perfectly! thank you so much!
