### ISSUE TITLE
Callback to let the underlying view knows the Rect projected from the entry

### ISSUE THREAD

**Issue by keithcml** [huri000/SwiftEntryKit#234]
**Is your feature request related to a problem? Please describe.**
I use SwiftEntryKit to show a bottom sheet, sometimes with text field so including keyboard. The underlying view controller should be interactable so I need to know the area that the Entry masked the underlying view. Then I can adjust the content size of the underlying scroll view.

**Describe the solution you'd like**
When EKContentView changes its frame, it can post its updated frame out.

**Comment by huri000** [comment]
Unfortunately, I don't have the time to look into it, but feel free to open a PR with your solution for me to review.
