### ISSUE TITLE
How do I access value inside textfields that I have inputted?

### ISSUE THREAD

**Issue by h36ahmed** [huri000/SwiftEntryKit#235]
This is regarding Forms in the library. 
I looked at the example and when you tap the button, you are simply dismissing the view. I want to be able to get the text fields data inputted by the user to further process. How should I go about doing that?

`
let buttonFont = AppTheme.TextStyle.button.font
        
        let buttonStyle = EKProperty.LabelStyle(
            font: buttonFont,
            color: EKColor(AppTheme.Color.onPrimary.value)
        )
        
        let title = EntryHelpers.getTitleLabelContent(text: formUIModel.title)
        
        let textFields = formUIModel.textFields.map { (field) -> EKProperty.TextFieldContent in
            return EntryHelpers.getTextFieldContent(textUIModel: field)
        }
        
        let button = EKProperty.ButtonContent(
            label: .init(text: formUIModel.button.text, style: buttonStyle),
            backgroundColor: EKColor(AppTheme.Color.primary.value),
            highlightedBackgroundColor: EKColor(AppTheme.Color.primaryVariant.value)) {
                [weak self] in
                self?.completeFormAction(action: formUIModel.button.action,
                                         textContent: textFields[0].textContent)
        }
        
        
        let contentView = EKFormMessageView(
            with: title,
            textFieldsContent: textFields,
            buttonContent: button
        )
        
        
        SwiftEntryKit.display(
            entry: contentView,
            using: formUIModel.attributes
        )
`

**Comment by huri000** [comment]
Please 👀`textContent` property in `TextFieldContent`. like this: `textField.textContent`. lemme know if that solved it for you.

**Comment by h36ahmed** [comment]
Solved. Thanks

**Comment by nungnung** [comment]
Could you explain more, please? Where could I add textContent property in the following function?

```
class func mobile(placeholderStyle: EKProperty.LabelStyle,
                      textStyle: EKProperty.LabelStyle,
                      separatorColor: EKColor,
                      style: FormStyle) -> EKProperty.TextFieldContent {
        let mobilePlaceholder = EKProperty.LabelContent(
            text: "Mobile Phone",
            style: placeholderStyle
        )
        return .init(keyboardType: .decimalPad,
                     placeholder: mobilePlaceholder,
                     tintColor: style.textColor,
                     displayMode: displayMode,
                     textStyle: textStyle,
                     leadingImage: UIImage(named: "ic_phone_light")!.withRenderingMode(.alwaysTemplate),
                     bottomBorderColor: separatorColor,
                     accessibilityIdentifier: "mobilePhoneTextField")
    }
```
