### ISSUE TITLE
Getting a reference to current entryWindow

### ISSUE THREAD

**Issue by Maxlufs** [huri000/SwiftEntryKit#236]
**Is your feature request related to a problem? Please describe.**

How to get a reference to the current entryWindow?

**Fact 1**: I have a UIApplication.getTopmostViewController() function and it does what the name suggests and it starts looking from `UIApplication.shared.keyWindow?.rootViewController` (which apparently just got [deprecated](https://developer.apple.com/documentation/uikit/uiapplication/1622924-keywindow) in iOS 13 so soon I will need to look from `UIWindow.shared.windows.last` which has `UITextEffectsWindow` mixed in ##whatface, and there's no way to check if the window `is EKWindow` since it's not a public class).
**Fact 2**: SwiftEntryKit creates an `EKWindow` on the top when an entry is presented by default.
**Fact 3**: I understand SwiftEntryKit currently provides `presentInsideKeyWindow` which I'm currently setting it to `true` to workaround this issue, then calling `dismiss` to allow my main window gain keyWindow control again, though i do have concerns that I might break other stuff down the road.

**Describe the solution you'd like**
`let entryWindow = SwiftEntryKit.display(entry:...)`, make it a `@discardableResult`

**Describe alternatives you've considered**
1. `let entryWindow = SwiftEntryKit.entryWindow` or ` SwiftEntryKit.entryWindows` if multiple, a static var similar to `isCurrentlyDisplaying`
2.  rename `presentInsideKeyWindow` to `presentAsKeyWindow` (reading the [source code](https://github.com/huri000/SwiftEntryKit/blob/master/Source/Infra/EKWindowProvider.swift#L65-L66) I believe this is what it means)

**Additional context**
I might be overthinking this and setting `presentInsideKeyWindow` to true is the clean answer I'm looking for. Would love some more insights on how to access the displayed window.

**Comment by huri000** [comment]
> `let entryWindow = SwiftEntryKit.display(entry:...)`, make it a `@discardableResult`

Although it's probably the cleaner approach, it won't be possible since the method works a asynchronically, and the window may not be instantiated at the time the method ends its execution.

> `SwiftEntryKit.entryWindow`

That I can do. It will be an optional computed variable, or alternatively, I can associate it with a state enum that has a value / non-value cases.

Not sure I understand what you were suggesting about renaming `presentInsideKeyWindow` though.

**Comment by Maxlufs** [comment]
ah i see, yeah i guess `let entryWindow = SwiftEntryKit.entryWindow` makes more sense if its async.

by renaming `presentInsideKeyWindow` I mean:
Since the entry will be an UIWindow instance no matter what, `presentInsideKeyWindow` means the entry will always be part of the current `keyWindow` hierarchy rather than having its own instance. 
On the other hand, `presentAsKeyWindow` means the entry is an UIWindow instance and when being set to true, a `makeKeyAndVisible()` has been called somewhere internally.

**Comment by Maxlufs** [comment]
My main issue is how to integrate SwiftEntryKit with logic of `UIApplication.getTopmostViewController()` a cleaner way.

**Comment by huri000** [comment]
Please use `1.2.1`. `EKWindow` is exposed statically as an optional computed variable via `SwiftEntryKit`.
I believe that's the solution you were looking for.

**Comment by Maxlufs** [comment]
looks good. thank you @huri000 !
