### ISSUE TITLE
Unable to display any alert in iOS 13

### ISSUE THREAD

**Issue by Haadia** [huri000/SwiftEntryKit#237]
I'm using the SwiftEntryKey using mentioned flow and while it works perfectly in devices running iOS 12, I'm unable to see anything being presented in iOS 13.

**Comment by huri000** [comment]
Might [this](https://github.com/huri000/SwiftEntryKit/pull/213#issuecomment-540514809) be a solution? Are you using scene delegate in your app?

**Comment by huri000** [comment]
PR was merged and iOS13 fix is available on `1.2.0`. lemme know if it works for you. 
In addition to #213, please also 👀 #211 (a related issue about multiple window setup in your project's `plist`).

**Comment by huri000** [comment]
Closing. Please see my previous comment and let me know if the issue persists (I will revisit if it does).
