### ISSUE TITLE
Swipe down to dismiss Entry

### ISSUE THREAD

**Issue by asikand** [huri000/SwiftEntryKit#240]
**Is your feature request related to a problem? Please describe.**
The current version of the library although it supports custom exit animations does not seem to support swiping down to dismiss an entry.

**Describe the solution you'd like**
If possible, create another flag in `.enable` called something like `direction`. I want to present an Entry up from the bottom of the screen and then dismiss it by dragging down and then have it also exit from the bottom of the screen. 

**Describe alternatives you've considered**
I've been looking through the code, especially EKContentView and EKAttributes + Scroll

**Comment by huri000** [comment]
Hi @asikand,
Perhaps I didn't quite understand your problem (If so, I'd appreciate if you could provide further detail), but I should state that`SwiftEntryKit` does support a swipe-to-dismiss gesture. Have you set up the example project yet? ^^

**Comment by asikand** [comment]
There are only two options in `attributes.scroll`. 

`.enabled` lets you scroll the Entry in both directions (pullback animation when user swipes toward bottom of screen), swipe toward top of screen to dismiss. 

`.edgeCrossingDisabled` which lets you swipe toward the toward the top of the screen to dismiss and does not allow scrolling toward the bottom of the screen. 

I need to be able to specify whether the dismissal should result from a **swipe toward the bottom of the screen** instead of a **swipe toward the top of the screen**

**Comment by seop-archisketch** [comment]
Have you tried the example project from this Github repository? All of the ones presented *from the bottom* are dismissable by scrolling downward.

**Comment by asikand** [comment]
Let me check the code and get back to you, perhaps I'm missing something.

**Comment by asikand** [comment]
I'm presenting a View Controller and not a view? Does this make any difference?

**Comment by asikand** [comment]
Issue was fixed by initializing attributes with `EKAttributes.bottomFloat` instead of just `EKAttributes()`

**Comment by omarojo** [comment]
So there is no way to specify which direction you wanna allow to dismiss ? 
regardless of which `.position` property you set ? 

ex.
`var attributes: EKAttributes = .topFloat`

but allow the user to dismiss either swiping up or swiping down. (both)

**Comment by huri000** [comment]
Nope. Not at the moment.

**Comment by pcentieiro** [comment]
Hello!

I'm looking forward to set the swipe direction. Any idea if it will be possible in the future, or how we can set it up, if we want it to?

Thanks and great job btw!
