### ISSUE TITLE
Displaying and Enqueuing Entry does not work.

### ISSUE THREAD

**Issue by seop-archisketch** [huri000/SwiftEntryKit#241]
**Describe the bug**
I would like to display an entry, and enqueue another one to be displayed after.  But when I call the functions consecutively, entry does NOT appear.   (The background of the entry is applied, but the entry does not appear)

**To Reproduce**
``` swift
SwiftEntryKit.display(entry: firstEntry, using: attributes)
attributes.precedence = .enqueue(priority: .normal)
SwiftEntryKit.display(entry: secondEntry, using: attributes)
```

**Expected behavior**
First entry is shown, and when it is dismissed, the next one in queue should appear.

**iPhone (please complete the following information):**
 - Device: iPhone 7, iPhone Xs
 - iOS Version: iOS 12, iOS 13
 - Xcode Version 11.1
 - SwiftEntryKit Release # 1.2.0

**Comment by huri000** [comment]
You need to lower the second entry's priority. That means you need to keep track of the priorities.
When you want to display the first entry you should state: `attributes.precedence = .enqueue(priority: .normal)`
When you want to display the second entry you should state: `attributes.precedence = .enqueue(priority: .low)`

An alternate workaround: you can set `EKAttributes.Precedence.QueueingHeuristic.value = .chronological` before displaying any entry to display entries in a chronological order. 

Let me know if that works for you.

**Comment by seop-archisketch** [comment]
Thanks for such a swift response. 
### DIFFERENTIATING PRIORITIES:
However, setting different priorities does not seem to work.

I believe it is not due to the priorities. The reason is that, it 'tries' to show the entries in the correct order.  It just gets stuck.

![IMG_4342](https://user-images.githubusercontent.com/49142815/67186578-4f1f6100-f423-11e9-9b1b-c68acd299a23.PNG)

As seen above, the dialog appears partially below the safe area, and the background is set to black with alpha as intended.  When I dismiss the 'partially shown' dialog by clicking background, the next one appears correctly.

The current situation is as below.
Entry A is shown,
(User makes some error)
Entry B is called (without `enqueue`),
Entry C is called (with `.enqueue(priority: .low)`)

It seems, Entry B is trying to be shown, but calling C with `.enqueue(priority: .low)` prevents it from opening.  Once B is dismissed by clicking background, C is shown properly.

### WORKAROUND
I was digging deep to find those properties, but I am not aware how I could set it.  
`attributes.precedence` does not have to property above to be set.  If the setting of this is global, then I tried calling the above line when initializing, and it still has to effect.  It shows the partially visible entry with full-screen background.

## On phones without the safe area, all that change is the background (thus the black screen with alpha).

**Comment by seop-archisketch** [comment]
@huri000 
I tried to build an example that would fail, and I could not reproduce the error.  I looked into the source, and found that when reusing the view (and assigning label text differently), it yielded the same error.
When I recreated the view every time, it worked fine! Thanks for trying to help.

Below is the code that would yield the empty view. 
``` swift
import UIKit
import SwiftEntryKit

class ViewController: UIViewController {
    private var attributes: EKAttributes = .init()
    private var width: CGFloat? = nil
    private var entryA = EntryA()
    @IBAction func startDemo(_ sender: UIButton) {
        startDemo()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        width = view.safeAreaWidth
    }

    private func startDemo() {
        showEntryA()
        DispatchQueue.main.asyncAfter(deadline: .now() + 3.0, execute: {
            self.showEntryBandEnqueueA()
        })
    }
    
    private func showEntryA() {
        attributes = .bottomFloat
        attributes.screenBackground = .color(color: EKColor.black.with(alpha: 0.7))
        attributes.entryBackground = .color(color: .white)
        attributes.displayDuration = .infinity
        attributes.screenInteraction = .dismiss
        attributes.entryInteraction = .dismiss
        attributes.entranceAnimation = .init(translate: .init(duration: 0.3, delay: 0.2, spring: .init(damping: 0.9, initialVelocity: 0)))
        attributes.exitAnimation = .init(translate: .init(duration: 0.2), fade: .init(from: 1.0, to: 0.0, duration: 0.2))
        attributes.positionConstraints.verticalOffset = 0
        attributes.positionConstraints.size = .init(width: .constant(value: width!), height: .intrinsic)
        attributes.statusBar = .ignored
        attributes.positionConstraints.safeArea = .empty(fillSafeArea: true)
        
        entryA.titleLabel.text = "FIRST OPEN"
        SwiftEntryKit.display(entry: entryA, using: attributes)
    }
    
    private func showEntryBandEnqueueA() {
        attributes = .bottomFloat
        attributes.screenBackground = .color(color: EKColor.black.with(alpha: 0.7))
        attributes.entryBackground = .color(color: .white)
        attributes.displayDuration = .infinity
        attributes.screenInteraction = .dismiss
        attributes.entryInteraction = .dismiss
        attributes.entranceAnimation = .init(translate: .init(duration: 0.3, delay: 0.2, spring: .init(damping: 0.9, initialVelocity: 0)))
        attributes.exitAnimation = .init(translate: .init(duration: 0.2), fade: .init(from: 1.0, to: 0.0, duration: 0.2))
        attributes.positionConstraints.verticalOffset = 0
        attributes.positionConstraints.size = .init(width: .constant(value: width!), height: .intrinsic)
        attributes.statusBar = .ignored
        attributes.positionConstraints.safeArea = .empty(fillSafeArea: true)
        
        entryA.titleLabel.text = "SECOND OPEN" // <-- At this point, there would be an empty view looking just like the screen shot above.
        SwiftEntryKit.display(entry: entryA, using: attributes)
        
        attributes.precedence = .enqueue(priority: .low)
        entryA.titleLabel.text = "FIRST OPEN"
        SwiftEntryKit.display(entry: entryA, using: attributes)
    }
}


extension UIView {
    var safeAreaWidth: CGFloat {
        get {
            return self.bounds.width - self.safeAreaInsets.left - self.safeAreaInsets.right
        }
    }
}
```
