### ISSUE TITLE
Multiple entries exist simultaneously

### ISSUE THREAD

**Issue by fanglinwei** [huri000/SwiftEntryKit#245]
If I want to display multiple Entryes at the same time, such as toast and alert, what should I do? It seems that the source code of SwiftEntryKit does not support this feature.

**Comment by huri000** [comment]
Hi, that's not possible at the moment. 
The subject came up several times. the library offers [alternate](https://github.com/huri000/SwiftEntryKit/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+multiple) solutions though.

**Comment by fanglinwei** [comment]
@huri000 
These features are very good, I like it very much, but I think there may be multiple item pop-up prompts for an application. I tried to fork SwiftEntryKit and split the`EKWindowProvider` class so that he is no longer a singleton, but each one.`SwiftEntryKit` has its own`EKWindowProvider`, which allows you to display multiple entries at the same time by initializing multiple SwiftEntryKit classes.


```swift
public final class SwiftEntryKit {
    
    public static let shared = SwiftEntryKit()
    
    let windowProvider = EKWindowProvider()

    public init() {}

    public var isCurrentlyDisplaying: Bool {
        return isCurrentlyDisplaying()
    }

    public func isCurrentlyDisplaying(entryNamed name: String? = nil) -> Bool {
        return windowProvider.isCurrentlyDisplaying(entryNamed: name)
    }

    public func display(entry view: UIView, using attributes: EKAttributes, presentInsideKeyWindow: Bool = false, rollbackWindow: RollbackWindow = .main) {
        DispatchQueue.main.async {
            self.windowProvider.display(view: view, using: attributes, presentInsideKeyWindow: presentInsideKeyWindow, rollbackWindow: rollbackWindow)
        }
    }
}

other functions...

```

Use
```swift
/// Display A popup
static let toastA = SwiftEntryKit().
toastA.display(entry: contentView, using: attributes)
/// Display B popup
static let toastB = SwiftEntryKit()
toastB.display(entry: contentView, using: attributes)
```

The result is that the AB entry can be displayed at the same time.

**Comment by carles-estevadeordal** [comment]
@fanglinwei Your code is interesting, but I tried it and it breaks the display. For example: when a second simultaneous alert view is dismissed then Entries are not displayed anymore. Have you done any more progress towards this? I would love this feature.
