### ISSUE TITLE
Identify when a user has dismissed popup vs. programatically

### ISSUE THREAD

**Issue by markst** [huri000/SwiftEntryKit#258]
So we can identify when a user has dismissed a popup rather than programatically.

**Comment by sashakid** [comment]
What is the issue?

**Comment by cha777** [comment]
Use dismiss entry method in your popup and have a callback for attributes life cycle in the root view

In your popup view
```
SwiftEntryKit.dismiss(.specific(entryName: "Entry Name"))
```

In your root view presenting the popup view
```
var attributes: EKAttributes = .toast
attributes.lifecycleEvents.didDisappear = {
    // Popup dismissed
}

SwiftEntryKit.display(entry: MyPopup(), using: attributes)
```

**Comment by markst** [comment]
Yes, but I’m unable to identify if dismissed by user interaction or programmatically

**Comment by huri000** [comment]
Hey! I don't think I'm gonna have the time for implementing it, but please feel free to do so and PR it.
