### ISSUE TITLE
Crash with no error when assigning entryBackground

### ISSUE THREAD

**Issue by jacobokoenig** [huri000/SwiftEntryKit#259]
**Describe the bug**
When assigning an entry background, the app crashes with no explanation.

**To Reproduce**
Create a set of attributes and assign color white:
var attributes                          = EKAttributes()
attributes.entryBackground              = .color(color: EKColor.white)

**iPhone (please complete the following information):**
 - Device: iPhone 11 Pro
 - iOS Version: iOS 13.1
 - Dependency Manager Version Cocoapods
 - SwiftEntryKit Release # 1.2.3

**Comment by huri000** [comment]
Hi, this shouldn't happen. I suspect it's a cached pod issue. Could you please try to:
- Update cocoapods (`sudo gem install cocoapods`)
- Delete derived data dir content.
- Clean project/build.
- `pod cache clean --all`
- `pod deintegrate`
- `pod install`

does the example project reproduce it as well?

**Comment by jacobokoenig** [comment]
Thank you. It was solved that way. I still have an issue, but will open on a separate thread.
