### ISSUE TITLE
How to display entry in specified uiviewcontroller, instead of a new window?

### ISSUE THREAD

**Issue by linshizai** [huri000/SwiftEntryKit#261]

**Comment by huri000** [comment]
This behavior is not currently supported. Why wouldn't you use a standard modal presentation for that?
i.e `present(_, animated:_, completion:_)`.

**Comment by asar1** [comment]
Any chances of this functionality in near future?

**Comment by yeguizhong** [comment]
In iPad, it would be very useful if we could specify adding to a specific UIViewController or UIView. I hope this feature can be supported.
