### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by talshr** [huri000/SwiftEntryKit#262]
**Describe the bug**
I'm getting "Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler" when compiling.

**To Reproduce**
Open on Xcode 11.2.1 and compile

**Comment by huri000** [comment]
That may happen between Xcode updates. I will be able to check that in a few hours.
In the meantime, could you please try cleaning the pods and build directory (e.i derived data) and then rebuild?

**Comment by talshr** [comment]
Deleting derived data solved it!
