### ISSUE TITLE
when displayed controller contains Alert, can't coexist

### ISSUE THREAD

**Issue by hydyy** [huri000/SwiftEntryKit#270]
custom alert use SwiftEntryKit, when display viewcontroller contain's alert, can't work...

**Comment by sashakid** [comment]
And what do you expect? It's not clear

**Comment by hydyy** [comment]
they can coexist?

**Comment by rebeloper** [comment]
What @hydyy  means is that by default UIAlertControllers are presented above the entry. If the entry is taller than half the screen height the alert is covered by it. The alert also unresponsive to touches.

Solution:

1. `attributes.entryInteraction = .delayExit(by: TimeInterval(Int.max))` to allow touches on UIAlertController
2. `SwiftEntryKit.display(entry: viewControllerToPresent, using: attributes, presentInsideKeyWindow: true)` to make the entry window keyAndVisible (in other words the active one)

Side notes: 

- SEK shows these entries on a new window. By default the main window of the app remains the active even if the entry is shown (`presentInsideKeyWindow` is `false` by default)
- When the entry is dismissed the entry window also loses it's "key and visible"-ness, the main window automatically again becomes keyAndVisible (when I say "automatically" I mean SEK cleverly does this)

**Comment by huri000** [comment]
@hydyy not quite sure what you meant by `custom alert`, but in case @rebeloper guessed it right and you referred to a native `UIAlertController` coexistence w/ a swift entry kit once, you could either do what @rebeloper suggested, or you could display the native alert controller directly from a displayed view controller entry (by using the presenting view controller as the presenter of the alert). Either way, both cannot be interacted by the user at the same time - one must be on top of the other.

Closing this for now. Please try to be a bit more specific when opening issues for the library.

![Simulator Screen Shot - iPhone 8 - 2020-05-16 at 15 09 34](https://user-images.githubusercontent.com/5504255/82121796-a1411e80-9787-11ea-8ac4-bc439ac9079b.png)

**Comment by asar1** [comment]
with windowlevel.normal alert is behind the presented view.
any solution?
