### ISSUE TITLE
EKContentView.panGestureRecognized(gr:) crash

### ISSUE THREAD

**Issue by vvlee** [huri000/SwiftEntryKit#277]
**Describe the bug**
get crash from firebase:

Fatal Exception: NSInternalInconsistencyException
NSLayoutConstraint constant is not finite! That's illegal. constant:nan firstAnchor:<NSLayoutYAxisAnchor:0x283e76380 "SwiftEntryKit.EKContentView:0x104309e60.top"> secondAnchor:<NSLayoutYAxisAnchor:0x283e4ea00 "SwiftEntryKit.EKWrapperView:0x1043236b0.top">

Use SnapKit layout custom view.

**iPhone:**
 - Device: iPhone 11
 - iOS Version: 13.3.1 (17D50)
 - Xcode Version 11.3.1 (11C504)
 - Dependency Manager Version COCOAPODS: 1.8.4
 - SwiftEntryKit Release # 1.2.3

**Additional context**

        let notificationView = NotificationView()
        var attributes = EKAttributes()
        attributes.name = "Notification Alert"
        attributes.position = .top
        attributes.displayDuration = 3
        attributes.entryBackground = .color(color: .white)
        let shadowColor = UIColor(0x999999FF)
        attributes.shadow = .active(with: .init(color: .init(shadowColor), opacity: 1, radius: 8, offset: CGSize(width: 0, height: 1)))
        attributes.positionConstraints.safeArea = .overridden
        attributes.entryInteraction.customTapActions.append {
            Logger.debug("Handle inapp notification action.")
        }
        SwiftEntryKit.display(entry: notificationView, using: attributes, presentInsideKeyWindow: false)

**Comment by huri000** [comment]
Issue fixed in `1.2.7`.
