### ISSUE TITLE
Dismiss specific entry not working

### ISSUE THREAD

**Issue by app-web-dev** [huri000/SwiftEntryKit#281]
**Describe the bug**
I have a View Controller which shows two entry at sam time some times, I would like to dismiss one and keep the other one, when I use SwiftEntryKit.dismiss(.prioritizedLowerOrEqualTo(priority: .normal)) or SwiftEntryKit.dismiss(.specific(entryName: "p")) it still dismiss both entries.

**To Reproduce**
N/A

**Expected behavior**
Dismiss only one entry.

**Screenshots**

**iPhone (please complete the following information):**
 - Device: iPhone Pro
 - iOS Version: 13.3
 - Xcode Version 11.3

**Additional context**

**Screenshots / Video Links**

 @objc func loadMessagesData() {
        if firstTimeShow {
            ViewUtility.showProcessingNote(text: "Loading your messages...")
            firstTimeShow = false
        }
        ConversationViewModel.conversations(messagesTableView: self.messagesTableView) { (conversations, error) in
            if error == nil {
                self.conversations = [Conversation]()
                self.conversations = conversations
                DispatchQueue.main.async {
                    SwiftEntryKit.dismiss(.prioritizedLowerOrEqualTo(priority: .normal))
                    SwiftEntryKit.dismiss(.specific(entryName: "p"))
                }
                self.messagesTableView.reloadData()
            } else {
                Crashlytics.sharedInstance().recordError(GeneralUtility.createError(code: FIRESTORE_FAILED_ERROR_CODE, text: "error getting conversations \(error!)"))
                ViewUtility.showAlert(self, message: error!.localizedDescription, title: NSLocalizedString("Error", comment: ""), mode: .error)
            }
        }
    }

**Comment by huri000** [comment]
Sorry for the delay - a sample project would be much appreciated here, as it takes a long time for me to build one for any open issue. Please upload it here.

**Comment by huri000** [comment]
Closing as the issue seems to be dormant. Please see my previous comment and feel free to comment with more intel
