### ISSUE TITLE
is It possible to toast exactly below navigation bar?

### ISSUE THREAD

**Issue by spyrosskordos** [huri000/SwiftEntryKit#282]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by huri000** [comment]
Not at the moment. The library operates outside the main window and therefore agnostic to its content. As a workaround, you may be able to convert the point from the view controller's coordinate system into the main window and use this offset for your view.

**Comment by huri000** [comment]
Closing as the issue is not in the scope of the solution offered by the library.
