### ISSUE TITLE
Use of unresolved identifier 'FormFieldPresetFactory'

### ISSUE THREAD

**Issue by ibyteapps** [huri000/SwiftEntryKit#283]
Sorry to be a pain, but I'm stuck somewhere and looking for guidance. 

I've been using SwiftEntryKit for a while and I've managed to implement a lot of features. But I cannot compile the showSignupForm() function. 

I'm using version 1.2.3 on xcode 11.4.1. 

In other instances, EKColor throws an error and I have to use my own colours. 

Perhaps I've not implemented your project properly? 

I've added it to my pod.  

**Describe the bug**
I'm unable to compile the code for showing a form. 

**To Reproduce**
1. copy the showSignupForm() function to my project

**Expected behavior**
I expected the code to compile. 
<img width="1124" alt="Screenshot 2020-05-08 at 22 33 57" src="https://user-images.githubusercontent.com/10578050/81451287-0c816400-917c-11ea-936c-df19f9b0d038.png">

**Screenshots**

The code isn't compiling, no point of trying to run it.

**Comment by ibyteapps** [comment]
I've been able to resolve this by creating a new project. It seems the files were not integrating properly in my original project. Thanks for such a lovely pod.

**Comment by huri000** [comment]
Seems like it can be resolved by simply clearing the cache + reinstalling.
