### ISSUE TITLE
Nothing being displayed

### ISSUE THREAD

**Issue by galblank** [huri000/SwiftEntryKit#289]
**Describe the bug**
Running a basic test isn't showing anything.
My setup is : 
Tabbed view
1 Tab - MapView
2 Tab - TableView
I do not use story boards or xib files , everything is done programatically.
I do use Mortar for autolayout

**To Reproduce**
```
 let customView = UIView()
           customView.backgroundColor = .blue
           var attributes = EKAttributes()
           attributes.windowLevel = .normal
           attributes.precedence = .override(priority: .max, dropEnqueuedEntries: false)
           attributes.position = .center
           attributes.displayDuration = .infinity
           attributes.entryInteraction = .delayExit(by: 3)
           attributes.scroll = .disabled
           attributes.displayMode = .inferred
           attributes.entryBackground = .visualEffect(style: .prominent)
           attributes.popBehavior = .animated(animation: .init(translate: .init(duration: 0.2)))
           attributes.roundCorners = .all(radius: 10)
           let widthConstraint = EKAttributes.PositionConstraints.Edge.ratio(value: 0.9)
           let heightConstraint = EKAttributes.PositionConstraints.Edge.intrinsic
           attributes.positionConstraints.size = .init(width: widthConstraint, height: heightConstraint)
           let green = {
               // Do something useful
           }
           let blue = {

           }
           let black = {

           }
           attributes.entryInteraction.customTapActions.append(green)
           attributes.entryInteraction.customTapActions.append(blue)
           attributes.entryInteraction.customTapActions.append(black)
           SwiftEntryKit.display(entry: customView, using: attributes)
```

**Expected behavior**
It should show up

**iPhone (please complete the following information):**
 - iOS Version: [e.g. iOS9.3]
 - Xcode Version [e.g. 9.3]
 - Dependency Manager Version [e.g. CocoaPods 1.5.2, Carthage 0.29.0]
 - SwiftEntryKit Release # [e.g. 0.2.0]

**Additional context**

**Screenshots / Video Links**

**Comment by huri000** [comment]
It’s unclear what’s the expected height of the view. You set it to intrinsic which means the view would take responsibility for setting the height but I don’t see any such setup.

**Comment by huri000** [comment]
Closing. Please see my earlier comment about height constraint. Some of the example project samples may help you.
