### ISSUE TITLE
nothing happened

### ISSUE THREAD

**Issue by topcmm** [huri000/SwiftEntryKit#290]
Just a very simple test code:

import UIKit
import SwiftEntryKit

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        
        
    }

    func popupWindow() {
        let vc = TestViewController()
        SwiftEntryKit.display(entry: vc, using: EKAttributes.bottomToast)
    }
    @IBAction func clicked(_ sender: Any) {
        popupWindow()
    }
}

when I clicked the button, don't display anything

**Comment by huri000** [comment]
Setting the attributes like that is probably your problem. There is not enough information in either the view or the attributes to determine the constraints, and therefore nothing is shown. Please install the example project and look at the samples provided there. If anything is unclear please let me know.
