### ISSUE TITLE
is it possible to set accessibilityViewIsModal true

### ISSUE THREAD

**Issue by AmirCa84** [huri000/SwiftEntryKit#294]
is it possible to set accessibilityViewIsModal to true on EKWindow? All windows are siblings so this will ignore others window for accessibility purposes.

**Comment by huri000** [comment]
You are welcome to fork and open a pull request. Unfortunately, I don't have time to experiment with solutions to this ATM, but if you are able to, please feel free to PR for my review.

**Comment by huri000** [comment]
@AmirCa84, It turned out I had time to do this. :-) 
All `EKWindow` instances are marked `accessibilityViewIsModal = true`. That seems to work properly with all types of background interactions. Please give `1.2.5` a try.

**Comment by AmirCa84** [comment]
Really appreciated it. :)
