### ISSUE TITLE
How to show entries one after the other?

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [huri000/SwiftEntryKit#318]
Hi,

First off, thank you for this project. It's really useful.

I use this library to show push notifications received when the app is in the foreground. I show floats for each notification I receive.
Currently if I receive say, two push notifications at the exact same time, the first float is shown but it gets dismissed quickly to make way for the second float.

Is there a way to make these floats present one after the other? Respecting the duration.

I see that there is a queue functionality but the thing is these entries are created dynamically. The number of entries depend on the number of push notifications I receive at run time so I can't hardcode a priority level.

Is there any other way to achieve this?

**Comment by libern** [comment]
Same question here.

**Comment by KidsBen7** [comment]
Same problem 👍

**Comment by libern** [comment]
Using:

```
        attributes.precedence = .enqueue(priority: .normal)
```

**Comment by Isuru-Nanayakkara** [comment]
@libern Thanks! That worked.
