### ISSUE TITLE
Type of expression is ambigous without more context

### ISSUE THREAD

**Issue by lingxiao** [huri000/SwiftEntryKit#321]
**Describe the bug**

When declaring form using presets: 

`func ToastForm( title: String ){
    
    let tit = UIFont(name: FontName.regular, size: AppFontSize.body2)!
    let bod = UIFont(name: FontName.regular, size: AppFontSize.footer)!

    let title = EKProperty.LabelContent(
        text: title,
        style: .init(font: tit, color: EKColor(Color.offBlack))
    )

    let textFields = FormFieldPresetFactory.fields(
        by: [.email, .password],
        style: .light
    )
    
    let btn = EKProperty.ButtonContent(
        label: "save",
        backgroundColor: Color.grayTertiary,
        highlightedBackgroundColor: Color.grayTertiary.darker(by: 50)
    )

    let contentView = EKFormMessageView(
        with: title,
        textFieldsContent: textFields,
        buttonContent: btn
    )
    
    let attributes = centerToastFactory( ratio: 1/4, displayDuration: 100000 )
    SwiftEntryKit.display(entry: contentView, using: attributes)
}
`

I get `Type of expression is ambiguous without more context` for `    let btn = EKProperty.ButtonContent` line

**To Reproduce**
1. Go to 'Any project with SwiftEntryKit Latest installed, xCode latest, Swift-Latest-stable
2. paste code
3. compile

**Expected behavior**
Should compile

**Screenshots**

**iPhone (please complete the following information):**
 - Device: iPhoneX
 - iOS Version: iOS 14.1
 - Xcode Version Latest
 - Dependency Manager Version Pod latest
 - SwiftEntryKit Release #Latest

**Additional context**

**Screenshots / Video Links**

**Comment by huri000** [comment]
Hey @lingxiao. I had no problem with this code:

```Swift
let btn = EKProperty.ButtonContent(
    label: .init(
        text: "Got it!",
        style: .init(
            font: MainFont.bold.with(size: 16),
            color: .amber,
            displayMode: displayMode
        )
    ),
    backgroundColor: .amber,
    highlightedBackgroundColor: .amber
)
```
Your `EKProperty.ButtonContent` initializer's parameters are incorrect. 
Make sure you're working with the latest release.
Please clean the build folder and `pod repo update` as well.
