### ISSUE TITLE
can not remove EKWindow in iOS 14.2

### ISSUE THREAD

**Issue by winterrain5** [huri000/SwiftEntryKit#322]
**Describe the bug**
when i user `SwiftEntryKit.dismiss()`, the content view is disappeared,but the EKWindow is always exist.

**iPhone (please complete the following information):**
 - Device: iPhoneSE2
 - iOS Version:iOS14.2
 - Xcode Version: 12.0.1
 - Dependency Manager Version CocoaPods 1.10.0.rc.1
 - SwiftEntryKit Release [1.2.3]

**Additional context**

**Screenshots / Video Links**
<img width="1792" alt="WX20201112-104151@2x" src="https://user-images.githubusercontent.com/15688369/98888886-cb279380-24d3-11eb-970e-0d523f51ab57.png">

**Comment by Jayxiang** [comment]
怎么解决的？

**Comment by huri000** [comment]
The latest release (1.2.7) patched this bug.
