### ISSUE TITLE
Constraints are not working

### ISSUE THREAD

**Issue by IKorabel** [huri000/SwiftEntryKit#326]
Hello, I tried to use custom view with bottomToast Attribute. I've set all constraints in interface builder, but however the interface is still displayed incorrectly. How can I fix it? Thank you!

Here is the code and screenshots 
<img width="878" alt="Снимок экрана 2020-11-30 в 02 32 43" src="https://user-images.githubusercontent.com/43014903/100561056-08539a00-32b8-11eb-8a58-f46eb9ff771e.png">
![photo_2020-11-30 02 59 44](https://user-images.githubusercontent.com/43014903/100561093-20c3b480-32b8-11eb-9f32-1bbdb3466107.jpeg)
![photo_2020-11-30 02 59 41](https://user-images.githubusercontent.com/43014903/100561104-2620ff00-32b8-11eb-8f98-3d6417605976.jpeg)

**Comment by huri000** [comment]
Hey. Please refer to the example project for best practices on how to write entries. There are plenty of similar use cases in there.
