### ISSUE TITLE
Floating top notifications shold be scrollable

### ISSUE THREAD

**Issue by stherold** [huri000/SwiftEntryKit#328]
**Is your feature request related to a problem? Please describe.**
When text on the notification overflows the screen it is imposible to read the truncated part.

**Describe the solution you'd like**
The view should be scrollable.

**Additional context**
![image](https://user-images.githubusercontent.com/64915710/102239483-31e70500-3ef7-11eb-82a4-2412b3ab48d4.png)

**Comment by huri000** [comment]
Hey. It depends on the use case. But the banner notification views are built to provide a banner experience so the content should be short and punchy.

**Suggestions:**
1. You could use `EKAttributes.PositionConstraints.Size` to limit the height and upon interaction redirect to a screen showing the full contents
2. Build your own entry layout. This shouldn't be hard - see samples that use scroll view in the example project.

**Comment by stherold** [comment]
Ah nice, thx for the help and input 👍

**Comment by mjunkmyjunk** [comment]
@stherold which example in the samples project was there this ability for scroll view? I can't seem to find it.

@huri000 its  supposed to be using this right?
```attributes.scroll = .edgeCrossingDisabled(swipeable: true)```

**Comment by stherold** [comment]
Hey there, I think we solved this somehow different, but thanks for help 👍
