### ISSUE TITLE
Unable to compile Demo - Nimble linker command exit code

### ISSUE THREAD

**Issue by omarojo** [huri000/SwiftEntryKit#349]
Anyone able to compile this project demo on Xcode 12 ?
I followed the steps to retrieve the submodules, and compiled the frameworks targets successfully before trying to run the demo.  

![image](https://user-images.githubusercontent.com/995265/125883078-4e497f9b-0c84-4e3e-bab5-0a3e1a2eac19.png)
![image](https://user-images.githubusercontent.com/995265/125883103-d1ccb15f-f4e7-450b-aaaa-49dd1d73eade.png)

**Comment by omarojo** [comment]
so I disabled TESTs and I was able to run in Device.

![image](https://user-images.githubusercontent.com/995265/125888546-7acc75e5-6aaa-43cb-879c-834f8fcafccb.png)

**Comment by huri000** [comment]
This was organically addressed in 2.0.0 by removing Nimble and Quick
