### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by brave723** [huri000/SwiftEntryKit#362]
**Describe the bug**
our application has presented a UIAlertController (<UIAlertController: 0x10c84c400>) of style UIAlertControllerStyleActionSheet from SwiftEntryKit.EKRootViewController (<SwiftEntryKit.EKRootViewController: 0x108064800>). The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem. If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.16  

 
 
**iPhone (please complete the following information):**
 - iOS Version: [15.0.2]
 - SwiftEntryKit Release # [1.2.7]

**Comment by multinerd** [comment]
https://stackoverflow.com/questions/24224916/presenting-a-uialertcontroller-properly-on-an-ipad-using-ios-8
