### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by wonder2011** [huri000/SwiftEntryKit#368]
Hello @aaronbrethorst @markst @RoCry @Blackjacx @ss18 . I am starting to use this library in a huge project. It seems to me an excellent library but I see that apparently it is not currently being maintained. Do you plan to continue maintaining this library?

**Comment by NikhilGangurde** [comment]
same here I have used this library for a bigger project and I got stuck in one issue now I have to find a workaround for that no one is replying to my question.

**Comment by wonder2011** [comment]
I think this library is dead.

**Comment by huri000** [comment]
There doesn’t seem to be critical issue to address and the library is working as expected. Closing this
