### ISSUE TITLE
Unable to install via CocoaPod

### ISSUE THREAD

**Issue by siyao1030** [huri000/SwiftEntryKit#4]
I added 
> pod 'SwiftEntryKit', '0.1.2'

and ran pod install

I get this message every time :(
> [!] Unable to find a specification for `SwiftEntryKit (= 0.1.2)`

**Comment by huri000** [comment]
Hi @siyao1030,
Thanks for the report.
What version of CocoaPods are you using? Please make sure it's 1.5.0 at least.
I'm not sure what is causing the issue, but you can try several steps to resolve it.
1. Delete Podfile.lock
2. Run "pod deintegrate" to remove the pods from your project.
2. Run "pod repo update" to make sure the cache is synced.
3. Make sure you specify in your Podfile: source 'https://github.com/CocoaPods/Specs.git' (as the installation guide instructs)
3. Run "pod install".

Please let me know if those helped,

**Comment by siyao1030** [comment]
Thanks for such quick response!

I realized there were some issues connecting to cocoaPod master, so running
pod repo remove master
pod setup
pod install
fixed it for me.

However, when I try to build, I get this build error from SwiftEntryKit.
<img width="699" alt="screen shot 2018-05-10 at 1 39 07 pm" src="https://user-images.githubusercontent.com/2103837/39893114-a46bd002-5457-11e8-985c-cd53f3ae1ec2.png">

I am currently using XCode 9.2, Swift 4 and iOS 10+.

**Comment by huri000** [comment]
Glad it helped.
Please try using _'0.1.3'_ version instead. The hashable thingy should be fixed now (Though it's weird the code compiled perfectly for me with it since it didn't have the `hashValue` computable property)

**Comment by huri000** [comment]
I've added support for Hashable in '0.1.4' with protocol implementation. Future versions will have a queueing feature for banners and popups to present them 1 by 1. So it is a necessary boilerplate.
You can either pod install 0.1.3 or 0.1.4 with the Hashable using any version of Xcode 9.x.y.

Let me know if it fixed it for you so I can close the current thread.

**Comment by siyao1030** [comment]
It works now! Thank you so much for your help :D
