### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by huri000** [huri000/SwiftEntryKit#45]
SwiftEntryKit supports Carthage and CocoaPods. It could be useful to support SwiftPM as well.

**Comment by huri000** [comment]
Pending SwiftPM support of system libraries (UIKit).

**Comment by phynet** [comment]
Hi, I'm resurrecting this thread. Sorry if isn't expected. What are the dependencies needed to support SPM?  is in scope? do you need help for this? thank you 😄
