### ISSUE TITLE
Showing EKPopUpMessageView close EKFormMessageView

### ISSUE THREAD

**Issue by iguron** [huri000/SwiftEntryKit#48]
First of all amazing goodlooking library!!!

I am showing a EKFormMessageView and pressing the button I validate the values of the textFields. And if one is worng I want to show EKPopUpMessageView like a Warning. But this action closes the FormMessageView. Why? Is there any chnace to keep the EKFormMessageView until all textfields are ok?

Thanks in advance.

**Comment by huri000** [comment]
Hi @iguron,

Could you please denote SwiftEntryKit version you are using? Besides - 

Can you attach the relevant code? Mostly EKFormMessageView creation?

EKFormMessageView's designated initializer receives an `EKProperty.ButtonContent` instance as a parameter, which defines the action which supposes to take place on `touchUpInside` event. 
It should not close the form unless you use `SwiftEntryKit.dismiss()` in one of the buttons' actions as in the example project.

**Comment by huri000** [comment]
Hi @iguron,
Sorry, I think I understand now what you are actually saying..
SwiftEntryKit does not currently support simultaneous entry display. It manages only a single entry at a time. I think that it might be worth to consider building a customized form and display your relevant warning below each text field (UX-wise).

**Comment by iguron** [comment]
Thanks for the quick Answer!!!

**Comment by huri000** [comment]
I’m considering this issue as a won’t fix. Please let me know if you think otherwise.
