### ISSUE TITLE
Allow presentation of Multiple Entries

### ISSUE THREAD

**Issue by ArtSebus** [huri000/SwiftEntryKit#51]
**Description**
Kits can be used for multiple UI Categories & Visual Response which can, in-some cases, appear on the screen at the same time. A typical use case would be Form & Notes. Users interact with form and notes shows the stage of completion. 

**Solution**
Allow multiple Kits to be visible at a given time. 

**Additional context**
As entry push itself on top of the stack and replaces active window, it might not be possible to use current implementation to push a new kit onto stack without dismissing the existing one. By separating controller "screenBackground" from entry, the above scenario can be achieved. 

**PS**
Very good job dear Sir.

**Comment by ArtSebus** [comment]
Hi @huri000 

I'll also take a look around and see if I can find a good answer to some of those question :D The library is so well written that rarely an issue is raised but I think the community must become more involved. Author shouldn't be the only one  involved in a +1k framework...

**Comment by ArtSebus** [comment]
btw to achieve above, I customized this heavily by choosing to go with the cv entry with cells inside. At first it was just and experiment but I was very amazed to see the entry performers to almost production level performance with no optimization. I'll reporting back with a few updates on this as well...

**Comment by huri000** [comment]
I think that I'll eventually insert another visual layer between the root view controller (EKRootViewController) and both the entry and the background views - they will be embedded inside another view that represents the whole context. 
Thus, I'll will be able to separate the context from the view controller and preparing the infrastructure for multiple entries presentation. 
This is the **first stage** IMO. It will have to be implemented either way.

The **second** stage should be installing a property or another construct in the EKAttributes, this property overrides the display priority and decides whether the entry is not intrusive meaining that it is to be displayed above the previous entry - to not pop the previous entry out upon its entrance.

This implementation basically solve most of the issues mentioned above. I still want to consider some issues the may arise a little bit more.
To conclude:
- Single Window - It will have to change its level according to the new entry. I've come to the conclusion that it entirely depends on the usage of the developer who integrate SwiftEntryKit into his project. This is a constraint the should not be handled by SwiftEntryKit.
- Separation of contexts within the root view controller.
- Addition of special property to EKAttributes.

**Comment by huri000** [comment]
Hi, I've decided it won't be implemented in the near future. I'm going to build a milestone plan an drop the issue over. But in the meantime, It'll be closed and marked as Delayed.

**Comment by mltbnz** [comment]
Is there some branch I can check out to have a look at how you did it @ArtSebus ?
