### ISSUE TITLE
Xcode 10 not use

### ISSUE THREAD

**Issue by c941010623** [huri000/SwiftEntryKit#53]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**iPhone (please complete the following information):**
 - iOS Version: [e.g. iOS9.3]
 - Xcode Version [e.g. 9.3]
 - Dependency Manager Version [e.g. CocoaPods 1.5.2, Carthage 0.29.0]
 - SwiftEntryKit Release # [e.g. 0.2.0]

**Additional context**

**Screenshots / Video Links**

**Comment by huri000** [comment]
Hi, you left the content of the message empty. Please explain are you trying to do, what error are you getting. Please fill the template of the issue. Thank
