### ISSUE TITLE
Example can not build and run

### ISSUE THREAD

**Issue by androidcn** [huri000/SwiftEntryKit#54]
Example can not build and run
Open SwiftEntryKit.xcworkspace
Build and run 
`SwiftEntryKit-master/Source/MessageViews/EKMessageContentView.swift:10:8: No such module 'QuickLayout'`

**Comment by huri000** [comment]
Please stick to the installation guide in the README.md.
Also, please review issue [#31](https://github.com/huri000/SwiftEntryKit/issues/31)

**Comment by RajManick** [comment]
Working Fine. Thanks for your support

**Comment by willMorph** [comment]
Hey there, It still seems to be showing for me, I cloned the file as listed in the installation guide, opened the workspace and tried running, and still seems to be giving me the same error.
