### ISSUE TITLE
Shadow won't work with round corners

### ISSUE THREAD

**Issue by RoCry** [huri000/SwiftEntryKit#55]
Reproduce in example: 
Just tap Floats-Top

![image](https://user-images.githubusercontent.com/1117026/41642086-eafdae16-7499-11e8-8814-a73fdfc43f11.png)

**Comment by huri000** [comment]
Thanks for reporting this issue. I'll look into it.

**Comment by huri000** [comment]
Resolved in 0.4.3. Cheers! 🎉
