### ISSUE TITLE
RoundCorners after the latest update

### ISSUE THREAD

**Issue by Banck** [huri000/SwiftEntryKit#59]
After the latest update my popups appears without roundCorners.

**To Reproduce**
Attribute:
   ```
     var attributes: EKAttributes
        attributes = .centerFloat
        attributes.windowLevel = .normal
        attributes.hapticFeedbackType = .success
        attributes.screenInteraction =  canBeClosed ? .dismiss : .absorbTouches
        attributes.entryInteraction = .absorbTouches
        attributes.roundCorners = .all(radius: 20)
        attributes.scroll = .enabled(swipeable: canBeClosed ? true : false, pullbackAnimation: .jolt)
        attributes.screenBackground = .color(color: UIColor(white: 0, alpha: 0.7))
        attributes.entryBackground = .color(color: UIColor(white: 0, alpha: 0.7))
        attributes.entranceAnimation = .init(scale: .init(from: 0.9, to: 1, duration: 0.4, spring: .init(damping: 1, initialVelocity: 0)), fade: .init(from: 0, to: 1, duration: 0.3))
        attributes.exitAnimation = .init(scale: .init(from: 1, to: 0.9, duration: 0.4, spring: .init(damping: 1, initialVelocity: 0)), fade: .init(from: 1, to: 0, duration: 0.3))
        attributes.displayDuration = .infinity
        attributes.border = .value(color: .black, width: 0.5)
        attributes.shadow = .active(with: .init(color: .black, opacity: 0.3, radius: 5, offset: .zero))
        attributes.positionConstraints.maxSize = .init(width: .offset(value: CGFloat(40.0.dp)), height: .intrinsic)
        attributes.positionConstraints.keyboardRelation = .bind(offset: .init(bottom: 10, screenEdgeResistance: 10))
        return attributes

```
 - Device: [all]
 - iOS Version: [9.0, 10.3.1, 11.4]
 - Xcode Version [9.4.1]
 - Dependency Manager Version [CocoaPods 1.5.2]
 - SwiftEntryKit Release # 0.5.0

**Comment by huri000** [comment]
Hi @Banck, 
Can you fill the whole template (iOS version, Xcode, etc...)? 
I tried to reproduce without a success.

**Comment by huri000** [comment]
In any case, please update to 0.5.1. There is a bug in the rollback window logic in 0.5.0.

**Comment by Banck** [comment]
The same issue with 0.5.1.
I haven't changed anything. The previous version was 0.4.2

**Comment by Banck** [comment]
Here is a xib example
[TwoButtonsAlertView.xib.zip](https://github.com/huri000/SwiftEntryKit/files/2130607/TwoButtonsAlertView.xib.zip)

**Comment by huri000** [comment]
In order to resolve this, you need to set the background-color via `attributes.entryBackground`.
Clear the view's backgroundColor in your xib and do instead:
`attributes.entryBackground = .color(color: .white)`
Let me know if that helps.

**Comment by huri000** [comment]
When I really think about it, It was supposed to be like this from the beginning. 
Developers shouldn't be able to customize entries halfway - You can stick to the example project presets which haven't changed by version 0.5.x and work just fine. :-)

**Comment by Banck** [comment]
@huri000 Hello!
Yes, if I do 
attributes.entryBackground = .color(color: .white)

and set clear color of my background view in the xib it works fine! Thanks.

**Comment by Banck** [comment]
but it was cool and useful when we could set color of background into the xib, and not in the attribute.

**Comment by huri000** [comment]
I'm glad it works!

> but it was cool and useful when we could set color of background into the xib, and not in the attribute.

In that case, one has to handle the round-corners himself by clipping to bounds and mnipulating the layer and not count on SwiftEntryKit to do so.

I consider it resolved.
