### ISSUE TITLE
iPhone X issue with presenting Alert right after previous was closed

### ISSUE THREAD

**Issue by Banck** [huri000/SwiftEntryKit#62]
**Describe the bug**
Hello!
There is issue when we are trying to show Alert when the previous one was closed.
**To Reproduce**
1. show alert "centerFloat"
2. In
 ```
SwiftEntryKit.dismiss(with: {
                
            })
```
show new alert "centerFloat"

Attribute: 
       
 

> var attributes: EKAttributes
>         attributes = .centerFloat
>         attributes.windowLevel = .normal
>         attributes.hapticFeedbackType = .success
>         attributes.screenInteraction =  canBeClosed ? .dismiss : .absorbTouches
>         attributes.entryInteraction = .absorbTouches
>         attributes.roundCorners = .all(radius: 20)
>         attributes.scroll = .enabled(swipeable: canBeClosed ? true : false, pullbackAnimation: .jolt)
>         attributes.screenBackground = .color(color: UIColor(white: 0, alpha: 0.7))
>         attributes.entryBackground = .color(color: .white)
>         attributes.entranceAnimation = .init(scale: .init(from: 0.9, to: 1, duration: 0.4, spring: .init(damping: 1, initialVelocity: 0)), fade: .init(from: 0, to: 1, duration: 0.3))
>         attributes.exitAnimation = .init(scale: .init(from: 1, to: 0.9, duration: 0.4, spring: .init(damping: 1, initialVelocity: 0)), fade: .init(from: 1, to: 0, duration: 0.3))
>         attributes.displayDuration = .infinity
>         attributes.border = .value(color: .black, width: 0.5)
>         attributes.shadow = .active(with: .init(color: .black, opacity: 0.3, radius: 5, offset: .zero))
>         attributes.positionConstraints.maxSize = .init(width: .offset(value: CGFloat(40.0.dp)), height: .intrinsic)
>         attributes.positionConstraints.keyboardRelation = .bind(offset: .init(bottom: 10, screenEdgeResistance: 10))

3. iPhone X freezes

**iPhone (please complete the following information):**
 - Device: only iPhone X
 - iOS Version: 11.
 - Xcode Version 9.4.1
 - Dependency Manager Version: CocoaPods 1.5.3
 - SwiftEntryKit Release # 0.5.1

**Comment by huri000** [comment]
Hi, I'll test it. Are you sure your SwiftEntryKit version is not 0.5.0 by any chance? 
I've already fixed that issue in 0.5.1.

**Comment by Banck** [comment]
@huri000 Have you found the reason of this bug?

**Comment by huri000** [comment]
Not yet. I’ll look into it this weekend and let you know.

**Comment by huri000** [comment]
@Banck, I've managed to reproduce the issue using iPhone X simulator.
Thanks for reporting this. The issue was due to missing the window hierarchy multiple times in the same run-loop. Really weird I admit. The solution was to execute each `SwiftEntryKit` a asynchronically on the main thread, so that the next action with have to be executed on the next run-loop.

**Comment by realvadim** [comment]
Hi there!

Unfortunately similar issue happens on iOS 9.3.2 (iPhone 5c).

If there is an entry displayed on the screen, showing a new entry will freeze the iPhone.

Although it works perfectly on iOS 10.*, 11.* and even iOS 9.2.

**Comment by realvadim** [comment]
Hi, @Banck Yes, I do.
![image](https://user-images.githubusercontent.com/22069538/42691654-ba815524-86ca-11e8-9740-79b9e7db2fc3.png)

**Comment by huri000** [comment]
Hi @realvadim, 
I'm looking into it. It seems like only in iOS 9.3 the layout is keeping updating the constraints in a loop. That's not supposed to happen of course. 
This is a different issue, with different circumstances, so, could you please open a different bug report? I'll keep you updated over there.

I'll keep you updated.

**Comment by realvadim** [comment]
Trying to solve the issue, I first called dismiss if there is an entry on the screen and in its completion present a new entry (Not that good, though acceptable). However, even doing so it does freeze in some cases.

**Comment by realvadim** [comment]
@huri000 I will open a new one. Thanks taking time to reply that fast. Appreciate it.

**Comment by huri000** [comment]
Sure :-) Thanks!
