### ISSUE TITLE
Round corner not working with customized view load from xib

### ISSUE THREAD

**Issue by dproton** [huri000/SwiftEntryKit#63]
Reproduce in example:
Just tap Custom-ViewController

![simulator screen shot - iphone 6s - 2018-06-27 at 11 30 21](https://user-images.githubusercontent.com/8925426/41953130-18e01850-79fe-11e8-8c55-4ff0c7f1c829.png)

**Comment by huri000** [comment]
I'm closing this issue - please review my previous comment. 
In version 0.5.2 the nib preset won't contain round corners in the attributes struct.
