### ISSUE TITLE
Blur doesn't work on iOS 10.3.1

### ISSUE THREAD

**Issue by Banck** [huri000/SwiftEntryKit#65]
**Describe the bug**
Regular bottom toast with blurred background doesn't work on iOS 10.3.1
**To Reproduce**
1. open demo project
2. show regular bottom toast

**Screenshots**
![image](https://user-images.githubusercontent.com/6259254/41960507-157b97a4-7a1a-11e8-8417-7aec643b9029.png)

**iPhone (please complete the following information):**
 - iOS Version: 10.3.1
 - Xcode Version 9.4.1
 - SwiftEntryKit Release # 0.5.1

**Comment by huri000** [comment]
@Banck - Just got to address this but I'm not able to reproduce it anymore. It's considered *resolved* IMO. Let me know if you think otherwise.
