### ISSUE TITLE
A way to set status bar color when app is using view controller-based status bar appearance

### ISSUE THREAD

**Issue by qizh** [huri000/SwiftEntryKit#66]
What if I can't set _view controller-based status bar appearance_ to NO because my app behavior is different? I would write an extension for `EKRootViewController` to override `preferredStatusBarStyle` getter but the class is not public so I can't. Is there a workaround?

**Comment by huri000** [comment]
Hi, sorry for the delay. The requested adjustment has been made and is available on 0.5.4.
Please read the [status bar section](https://github.com/huri000/SwiftEntryKit#status-bar). It's basically the same API as before, only the internal implementation has been changed.
Cheers!
