### ISSUE TITLE
Custom Interface

### ISSUE THREAD

**Issue by Michele404** [huri000/SwiftEntryKit#7]
How can I create a custom interface.
Example add two button with action, label, image or whatever else

**Comment by huri000** [comment]
Hi @Michele404,
There is pretty extensive readme but you can have a look at [those files](https://github.com/huri000/SwiftEntryKit/tree/master/Example/SwiftEntryKit/InAppPresets/Samples/NibExampleView). It's a custom nib example with pretty much what you are looking for.
As for the _button with action_ part, you have to implement it yourself, of course.  :-)

**Comment by huri000** [comment]
IMHO it has nothing to do with the map view. I need to see your code in order to understand what you are trying to accomplish, how the EKAttributes is configured. Can you post here the snippets?

**Comment by Michele404** [comment]
func mapView(_ mapView: MKMapView, didSelect view: MKAnnotationView)
    {
        if let annotationTitle = view.annotation?.title
        {
            print("User tapped on annotation with title: \(annotationTitle!)")
            
            // Create a basic toast that appears at the top
            var attributes = EKAttributes.centerFloat
            attributes.windowLevel = .normal
            // Set it's background to white
            attributes.entryBackground = .color(color: .black)
            
            // Animate in and out using default translation
            attributes.entranceAnimation = .translation
            attributes.exitAnimation = .translation
            
            let customView = UIView()
            let label = UILabel()
            label.text = "Test"
            customView.addSubview(label)
            SwiftEntryKit.display(entry: customView, using: attributes)
        }
    }


When the user tap on the Pin it should show the SwiftEntryKit view. It doesn't show.

**Comment by huri000** [comment]
The problem is here:
`      let customView = UIView()
        let label = UILabel()
        label.text = "Test"
        customView.addSubview(label)`
You need to set constraints to define the relationship between the child and its parent. In your case the child is `label` and the parent is `customView`, otherwise, the UIKit won't be able to show the label inside customView.

**Comment by Michele404** [comment]
I can't see the whole EKAttributes because it seems that EK is under the MapView and I can't see it.

**Comment by huri000** [comment]
I'm marking the issue as resolved.
