### ISSUE TITLE
App freezes on iOS 9.3.2 when displaying an entry and there is one shown already

### ISSUE THREAD

**Issue by realvadim** [huri000/SwiftEntryKit#73]
**Describe the bug**
While one entry is displayed on the screen, showing another entry freezes the app.

**To Reproduce**
1. Display an entry;
2. While one on the screen, display another one.
3. See the app frozen.

**Expected behavior**
Multiple entries are shown one after another.

**iPhone (please complete the following information):**
 - Device: iPhone 5c
 - iOS Version: iOS 9.3.2
 - Xcode Version 9.4.1
 - Dependency Manager Version CocoaPods 1.4.0
 - SwiftEntryKit Release 0.5.5

**Additional context**
Works perfectly on iOS 10.*, iOS 11.*, and even iOS 9.2.

**Comment by huri000** [comment]
Thanks for opening the issue.
A fix has been made and available on 0.5.6. 🎉
Please check it out and let me know.

**Comment by realvadim** [comment]
Thank you so much, @huri000!  It works perfectly now. Having a problem resolved within an hour is simply incredible. You are definitely the King of open source 👑 😉 👍

**Comment by huri000** [comment]
Thanks! Glad I could help.
