### ISSUE TITLE
Custom view does not appear on OS 11.3/iPhone-X

### ISSUE THREAD

**Issue by BitCrawler** [huri000/SwiftEntryKit#75]
Loading a custom view from a nib does not appear when called with SwiftEntryKit.display(...)

1. Write custom view and load from nib like in the demo app
2. Define attributes like in the demo app
3. call SwiftEntryKit.display(entry: MyView(), using: attributes)
-> nothing appear

**Expected behavior**
the view should appear

**iPhone (please complete the following information):**
 - Device: iPhone-X
 - iOS Version: 11.3
 - Xcode Version 9.4
 - Dependency Manager Version CocoaPods 1.5.2
 - SwiftEntryKit Release # 0.5

**Source**
class EditExpenseView: UIView {
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    init() {
        super.init(frame: .zero)
        setup()
    }
    
    private func setup() {
        fromNib()
        clipsToBounds = true
        layer.cornerRadius = 5
    }
}

extension NSObject {
    var className: String {
        return String(describing: type(of: self))
    }
    
    class var className: String {
        return String(describing: self)
    }
}

extension UIView {
    
    @discardableResult
    func fromNib<T : UIView>() -> T? {
        guard let contentView = Bundle(for: type(of: self)).loadNibNamed(type(of: self).className, owner: self, options: nil)?.first as? T else {
            return nil
        }
        addSubview(contentView)
        contentView.fillSuperview()
        return contentView
    }
}

        var attributes: EKAttributes
        
        attributes = .bottomFloat
        attributes.hapticFeedbackType = .success
        attributes.displayDuration = 3
        attributes.screenBackground = .clear
        attributes.entryBackground = .clear
        attributes.screenInteraction = .forward
        attributes.entryInteraction = .absorbTouches
        
        attributes.entranceAnimation = .init(translate: .init(duration: 0.5, spring: .init(damping: 0.9, initialVelocity: 0)),
                                             scale: .init(from: 0.8, to: 1, duration: 0.5, spring: .init(damping: 0.8, initialVelocity: 0)),
                                             fade: .init(from: 0.7, to: 1, duration: 0.3))
        attributes.exitAnimation = .init(translate: .init(duration: 0.5),
                                         scale: .init(from: 1, to: 0.8, duration: 0.5),
                                         fade: .init(from: 1, to: 0, duration: 0.5))
        attributes.popBehavior = .animated(animation: .init(translate: .init(duration: 0.3),
                                                            scale: .init(from: 1, to: 0.8, duration: 0.3)))
        attributes.shadow = .active(with: .init(color: .black, opacity: 0.3, radius: 6))
        attributes.positionConstraints.verticalOffset = 10
        attributes.positionConstraints.size = .init(width: .offset(value: 20), height: .intrinsic)
        attributes.positionConstraints.maxSize = .init(width: .constant(value: 375), height: .intrinsic)
        attributes.statusBar = .dark
        
//this works!
//        let myview:EditExpenseView = EditExpenseView()
//        myview.frame = CGRect(x: 10, y: 100, width: 200, height: 200)
//        self.view.addSubview(myview)
        
        SwiftEntryKit.display(entry: EditExpenseView(), using: attributes) -> **here the entry does not appear**

**Comment by huri000** [comment]
Custom views do work.
You need to use Auto Layout to define the size of your views. The height is inferred from the view unless you explicitly define the attributes to behave otherwise.
```Swift
attributes.positionConstraints.size = .init(width: .offset(value: 20), height: .intrinsic)
```
Set explicit height that is not intrinsic in order to acheive your goal OR use Auto Layout (not explicity setting the frame).

**Comment by huri000** [comment]
I'm closing this since that is a none-issue IMO. Just follow the example project preset for View From Nib.

**Comment by samsidd** [comment]
i am also unable to present custom views

**Comment by huri000** [comment]
Hi, 
Please see the custom view preset in the example project. As I said, SwiftEntryKit infers the height of your view from its intrinsic height in case you use Auto Layout. In case you don't you auto layout - `PositionConstraints` construct provides everything you need in order to make things size properly to your custom view (It is fully documented).
