### ISSUE TITLE
Status Bar Hidden

### ISSUE THREAD

**Issue by MoElnaggar14** [huri000/SwiftEntryKit#76]
I'm displaying a nib that have button 
In the dismiss for it I go to another VC but the status bar is hidden 
and when UI debugging I found myself instantiating my VC in the entryKit hierarchy not in mine

Anyone have idea how to fix this or the right way to do it ?   
** What I'm trying to do is to :
- show a nib (I did) --> success
- then click the button on it and make a transition to another VC (that the nib didn't come from) --> success but the issue above happened

**Comment by huri000** [comment]
Hi,
Your description is a bit unclear. Why did you close the issue? Is this relevant?

**Comment by MoElnaggar14** [comment]
hmm , i closed the issue because i solved it in my code and i thought i'm not right in description

anyway my issue was "i make a loadNib in ViewController and have a button when pressed this button i go to another view controller , when moved to another view controller , the status bar is hidden"

so i made a UI debugging that explain the issues "i go to view controller with pod root not my app root"

**Comment by MoElnaggar14** [comment]
i just call appdelegate and force root to start from this view Controller
