### ISSUE TITLE
Deployment target is 9.3, not 9.0

### ISSUE THREAD

**Issue by Banck** [huri000/SwiftEntryKit#78]
**Describe the bug**
Hello. The deployment target for SwiftEntryKit is 9.3 from carthage. It should be 9.0.

**To Reproduce**
1. install SwiftEntryKit through Carthage
**Expected behavior**
Should be 9.0
**Screenshots**
![](http://joxi.ru/xAe8abupoEKv2y.png)

**iPhone (please complete the following information):**
 - Xcode Version 9.4.1
 - Dependency Manager Version : Carthage 0.30.1
 - SwiftEntryKit version: 0.5.6

**Comment by huri000** [comment]
Sorry for the delay, I'll look into it in the next few days and possibly upload a new version.

**Comment by huri000** [comment]
Resolved in **0.5.7**. 🎉

**Comment by Banck** [comment]
Thanks! It works now.
