### ISSUE TITLE
How to set the value (not placeholder) to textfield for Forms preset?

### ISSUE THREAD

**Issue by yonlau** [huri000/SwiftEntryKit#79]
Any method could let me set the value into textfield which I already fill in last time in Forms preset?
How to get the callback/delegation if I did finish key-in at textfield from keyboard?

**Comment by huri000** [comment]
Hi, sorry for the delay. I'll look into it in the next few days and possibly release a version that contains the feature.

**Comment by huri000** [comment]
The issue was resolved just now - please use version **0.5.8**.
See [CHANGELOG](https://github.com/huri000/SwiftEntryKit/blob/master/CHANGELOG.md) for additional info. 🎉

**Comment by yonlau** [comment]
Good job! Thank you.
