### ISSUE TITLE
Error in pod files

### ISSUE THREAD

**Issue by Mina-Gerges** [huri000/SwiftEntryKit#89]
**Describe the bug**
1- Pods/SwiftEntryKit/SwiftEntryKit/Model/EntryAttributes/EKAttributes+DisplayPriority.swift:20:19: Type 'EKAttributes.DisplayPriority' does not conform to protocol 'Hashable'

**Comment by huri000** [comment]
Not enough information.
Please provide SwiftEntryKit version, Xcode version, Swift version and everything that is in the template according to the pattern provided.
Thanks!

**Comment by Mina-Gerges** [comment]
i recognized i was on version 0.1.1 for SwiftEntryKit  , So i write the newest version in my Podfile 0.5.8 but it gave me the following error 

> CocoaPods could not find compatible versions for pod "SwiftEntryKit":
>   In Podfile:
>     SwiftEntryKit (= 0.5.8)

I am using :
Xcode version 9.1 
Swift 4

**Comment by huri000** [comment]
That is probably a caching issue of CocoaPods. Not SwiftEntryKit. Try clearing your repo.
`pod cache clean --all` and `pod deintegrate`.

**Comment by Mina-Gerges** [comment]
That's the only CocoaPod that show this problem. I am already using many other pods in my project.

**Comment by huri000** [comment]
My guess is that the previously installed pod version was kept in your local repo. Trying what I suggested should solve the issue IMO. Please let me know if that works for you.

**Comment by Mina-Gerges** [comment]
The problem is the same after trying those line on terminal. 
Can i use this pod using frameworks or other way than terminal??

**Comment by huri000** [comment]
I think it is not a SwiftEntryKit but a CocoaPods' repo issue - Many developers including myself are using 0.5.8 without any installation issues. You may try 0.5.7 or one of the previous releases instead and see If this issue arise there as well.
You can use Carthage instead of CocoaPods.

**Comment by Mina-Gerges** [comment]
Thanks for your reply . I will try it with Carthage .

**Comment by Mina-Gerges** [comment]
I am going through the steps using Carthage but i don't know how to do the last step . 

To integrate SwiftEntryKit into your Xcode project using Carthage, specify the following in your Cartfile:
github "huri000/SwiftEntryKit" == 0.5.8

I don't know what is the Cartfile and how i access to it . Its my first time with Carthage.

**Comment by huri000** [comment]
You can read the installation guide for Carthage [here](https://github.com/Carthage/Carthage). :-)
I'm closing the issue since it is not directly related to SwiftEntryKit configuration.
