### ISSUE TITLE
Unable to run the Example Project

### ISSUE THREAD

**Issue by shaktiprakash099** [huri000/SwiftEntryKit#93]
I wanted to run the example project so i followed 
 the below  instruction guides 
Run git clone with --recurse-submodules, to include QuickLayout as submodule, likewise:

$ git clone --recurse-submodules https://github.com/huri000/SwiftEntryKit.git

But i got error like 
```ld: warning: directory not found for option```
```ld: framework not found Pods_QuickLayoutiOSDemo```
```clang: error: linker command failed with exit code 1 (use -v to see invocation)```
Kindly check the screenshot 
![screen shot 2018-08-25 at 2 00 06 pm](https://user-images.githubusercontent.com/31213820/44616535-393dfc80-a86f-11e8-80cb-8dc20d95e6b9.png)
**Expected behavior**
It should run Fine 

 - Device: Simulator 
 - iOS Version:  iOS11.3
 - Xcode Version [e.g. 9.3]
 - Dependency Manager Version . CocoaPods 1.5.2,

**Comment by huri000** [comment]
Can you change the run scheme to QuickLayout (framework target) and build. Then do the same with SwiftEntryKit (framework target) and build. Then try to run the demo again. Please let me know if that works for you.

**Comment by shaktiprakash099** [comment]
@huri000  thanks for your reply ,i tried also your approach but its not working either
see this ![Check this ](http://g.recordit.co/l0HSRwEaFp.gif)

**Comment by huri000** [comment]
From the gif it seems you run  QuickLayoutDemo instead of SwiftEntryKitDemo. 
Can you try again? This this time just run the frameworks and then run SwiftEntryKitDemo scheme.

**Comment by shaktiprakash099** [comment]
@huri000  Kindly check the complete gif i tried SwiftEntryKitDemo nothing happens  same error

**Comment by shaktiprakash099** [comment]
thanks @huri000  Yes it worked for me

**Comment by huri000** [comment]
Great! 🎉

**Comment by RaghavaNaidu46** [comment]
Hello Huri, You have done a great job it seems but unfortunately I couldn’t use your efforts. 
I have gone through some of the related issues but no solution works for me. After trying the above steps I'm getting this again. Make it consistent, please. 
```
ld: library not found for -lswiftXCTest
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by omarojo** [comment]
I'm getting the same error as well.  
@huri000 

Xcode Version 12.5 (12E262)

**Comment by Cxbin** [comment]
> Hello Huri, You have done a great job it seems but unfortunately I couldn’t use your efforts.
> I have gone through some of the related issues but no solution works for me. After trying the above steps I'm getting this again. Make it consistent, please.
> 
> ```
> ld: library not found for -lswiftXCTest
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```

You need to delete SwiftEntryKitTests in  TARGETS
